# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class AddExtractionToDocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    extraction: dict[str, Any] | None = Field(None, title='Extraction')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class AddExtractionToDocumentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['ok'] = Field('ok', title='Status')
    document_id: str = Field(..., title='Document Id')


class AggregationBucket(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str = Field(..., title='Label')
    value: str = Field(..., title='Value')
    count: int = Field(..., title='Count')


class AssignableUserResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    email: str = Field(..., title='Email')
    org_role: str | None = Field(None, title='Org Role')


class AssignableUsersListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    users: list[AssignableUserResponse] | None = Field(None, title='Users')


class AuthErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')
    hint: str | None = Field(None, title='Hint')


class BillingCheckoutResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['placeholder'] = Field('placeholder', title='Status')
    url: str = Field(..., title='Url')


class BillingInvoicesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['placeholder'] = Field('placeholder', title='Status')
    invoices: list[dict[str, Any]] | None = Field(None, title='Invoices')


class BillingPortalResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['placeholder'] = Field('placeholder', title='Status')
    url: str = Field(..., title='Url')


class BillingSubscriptionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['placeholder'] = Field('placeholder', title='Status')
    subscription: dict[str, Any] | None = Field(None, title='Subscription')


class BodyProcessReadingListReadingListProcessPost(BaseModel):
    file: bytes = Field(..., title='File')


class BriefcaseContextCheckResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    briefcase_id: str = Field(..., title='Briefcase Id')
    has_context: bool = Field(..., title='Has Context')


class BriefcaseContextResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    briefcase_id: str = Field(..., title='Briefcase Id')
    context: dict[str, Any] | None = Field(None, title='Context')


class BriefcaseCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=255) = Field(
        ..., description='Briefcase name', title='Name'
    )


class BriefcaseExportResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    briefcase_id: str = Field(..., title='Briefcase Id')
    format: str = Field(..., title='Format')
    download_url: str = Field(..., title='Download Url')


class BriefcaseInvalidateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    doc_ids: list[str] = Field(
        ...,
        description='Legal document IDs to invalidate',
        max_length=50,
        min_length=1,
        title='Doc Ids',
    )


class BriefcaseItemBatchResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    added: int = Field(..., title='Added')
    skipped: int = Field(..., title='Skipped')


class BriefcaseItemCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legis_id: constr(min_length=1) = Field(
        ..., description='Legal resource ID to add', title='Legis Id'
    )
    title: str | None = Field(None, description='Optional display title', title='Title')
    url: str | None = Field(None, description='Optional URL', title='Url')
    body: str | None = Field(
        None, description='Optional body text / content snippet', title='Body'
    )
    type: str | None = Field(
        None, description='Optional item type (e.g. legislation, case)', title='Type'
    )
    tags: list[str] | None = Field(None, description='Category tags', title='Tags')
    timestamp: int | None = Field(
        None, description='Unix ms timestamp for sorting', title='Timestamp'
    )


class BriefcaseItemNoteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, description='Optional note title', title='Title')
    body: constr(min_length=1) = Field(..., description='Note body text', title='Body')


class BriefcaseItemNoteResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    briefcase_item_id: str = Field(..., title='Briefcase Item Id')
    user_id: str = Field(..., title='User Id')
    title: str | None = Field(None, title='Title')
    body: str = Field(..., title='Body')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class BriefcaseItemNoteUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, description='Updated title', title='Title')
    body: constr(min_length=1) | None = Field(
        None, description='Updated body text', title='Body'
    )


class BriefcaseItemResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    briefcase_id: str = Field(..., title='Briefcase Id')
    legis_id: str = Field(..., title='Legis Id')
    title: str | None = Field(None, title='Title')
    url: str | None = Field(None, title='Url')
    body: str | None = Field(None, title='Body')
    type: str | None = Field(None, title='Type')
    tags: list[str] | None = Field(None, title='Tags')
    timestamp: int | None = Field(None, title='Timestamp')
    position: int | None = Field(0, title='Position')
    added_at: AwareDatetime | None = Field(None, title='Added At')


class BriefcaseNoteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, description='Optional note title', title='Title')
    body: constr(min_length=1) = Field(..., description='Note body text', title='Body')


class BriefcaseNoteResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    briefcase_id: str = Field(..., title='Briefcase Id')
    user_id: str = Field(..., title='User Id')
    title: str | None = Field(None, title='Title')
    body: str = Field(..., title='Body')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class BriefcaseNoteUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, description='Updated title', title='Title')
    body: constr(min_length=1) | None = Field(
        None, description='Updated body text', title='Body'
    )


class BriefcaseResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    active: bool | None = Field(True, title='Active')
    pinned: bool | None = Field(False, title='Pinned')
    position: int | None = Field(None, title='Position')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class BriefcaseShareResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    briefcase_id: str = Field(..., title='Briefcase Id')
    sharer_id: str = Field(..., title='Sharer Id')
    sharee_id: str = Field(..., title='Sharee Id')
    permission: str = Field(..., title='Permission')
    accepted_at: str | None = Field(None, title='Accepted At')
    revoked_at: str | None = Field(None, title='Revoked At')
    created_at: str = Field(..., title='Created At')


class BriefcaseSummarizeRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    doc_ids: list[str] = Field(
        ...,
        description='Legal document IDs (legisIds) to summarize',
        max_length=50,
        min_length=1,
        title='Doc Ids',
    )
    facets: list[str] | None = Field(
        ['overview', 'key_provisions', 'scope'],
        description='Facets to generate: overview, key_provisions, scope, risks, definitions, procedural, penalties',
        title='Facets',
    )


class BriefcaseUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=255) | None = Field(
        None, description='New name', title='Name'
    )
    pinned: bool | None = Field(
        None, description='Pin briefcase to top', title='Pinned'
    )
    active: bool | None = Field(
        None, description='Whether briefcase is active', title='Active'
    )


class ChatBriefcaseContextResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chat_id: str = Field(..., title='Chat Id')
    context: dict[str, Any] | None = Field(None, title='Context')


class ChatCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, title='Title')
    briefcase_id: str | None = Field(None, title='Briefcase Id')
    exclude_from_memory: bool | None = Field(False, title='Exclude From Memory')


class ChatCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')


class ChatDetailResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    title: str | None = Field(None, title='Title')
    briefcase_id: str | None = Field(None, title='Briefcase Id')
    exclude_from_memory: bool | None = Field(False, title='Exclude From Memory')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')
    messages: list[dict[str, Any]] | None = Field(None, title='Messages')


class ChatMessageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(..., title='Text')
    learning_mode: bool | None = Field(False, title='Learning Mode')
    model: str | None = Field('', title='Model')
    briefcase_doc_ids: list[str] | None = Field(
        None,
        description='Legal document IDs (legisIds) to include as RAG context',
        title='Briefcase Doc Ids',
    )
    briefcase_facets: list[str] | None = Field(
        None,
        description='Specific facets to include: overview, key_provisions, scope, risks, etc.',
        title='Briefcase Facets',
    )


class ChatMessagesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chat_id: str = Field(..., title='Chat Id')
    messages: list[dict[str, Any]] | None = Field(
        None,
        description="Array of chat messages. Each item: {role: 'user'|'assistant', content: str, created_at: str, id: str}.",
        title='Messages',
    )


class ChatSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    title: str | None = Field(None, title='Title')
    briefcase_id: str | None = Field(None, title='Briefcase Id')
    exclude_from_memory: bool | None = Field(False, title='Exclude From Memory')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class ChatTitleRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    messages: list[str] = Field(
        ...,
        description='Chat messages to generate title from (1-50 messages).',
        max_length=50,
        min_length=1,
        title='Messages',
    )


class ChatTitleResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., title='Title')


class ChatUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, title='Title')
    exclude_from_memory: bool | None = Field(None, title='Exclude From Memory')


class CitationCheckRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str = Field(
        ..., description='Document text or single citation to verify', title='Text'
    )


class CitationStatus(StrEnum):
    verified = 'verified'
    hallucinated = 'hallucinated'
    uncertain = 'uncertain'


class CitingDocument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legisId: str | None = Field('', title='Legisid')
    citation: str | None = Field('', title='Citation')
    sort_date: str | None = Field('', title='Sort Date')
    body_snippet: str | None = Field('', title='Body Snippet')


class ClarifyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ask: constr(min_length=1) = Field(
        ..., description="The user's question or request to clarify.", title='Ask'
    )
    context: dict[str, Any] | None = Field(
        None,
        description="Optional context to inform clarification. Common keys: 'jurisdiction' (str), 'document_type' (str), 'briefcase_id' (str), 'prior_messages' (list[str]). All keys are optional.",
        title='Context',
    )
    document_type: str | None = Field(
        '', description='Type of document for context', title='Document Type'
    )
    drafting_style: str | None = Field(
        '', description='Drafting style preference', title='Drafting Style'
    )
    parties: list[dict[str, Any]] | None = Field(
        None, description='Party details for context', title='Parties'
    )
    document_terms: dict[str, Any] | None = Field(
        None, description='Key terms for context', title='Document Terms'
    )
    compressed_references: list[str] | None = Field(
        None,
        description='Compressed reference summaries for context',
        title='Compressed References',
    )


class ClarifyResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clarified_ask: str = Field(..., title='Clarified Ask')
    questions: list[str] | None = Field(None, title='Questions')


class ClauseCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=255) = Field(
        ..., description='Clause name', title='Name'
    )
    content: constr(min_length=1) = Field(
        ..., description='Clause content/text', title='Content'
    )
    category: constr(max_length=100) | None = Field(
        None, description='Clause category', title='Category'
    )
    tags: list[str] | None = Field(None, description='Clause tags', title='Tags')
    metadata: dict[str, Any] | None = Field(
        None, description='Additional metadata', title='Metadata'
    )


class ClauseDatabaseResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., description='Database ID (same as org_id)', title='Id')
    name: str | None = Field('Default', description='Database name', title='Name')
    clause_count: int | None = Field(
        0, description='Number of clauses in database', title='Clause Count'
    )


class ClauseResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    content: str = Field(..., title='Content')
    category: str | None = Field(None, title='Category')
    tags: list[str] | None = Field(None, title='Tags')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    created_by: str | None = Field(None, title='Created By')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class ClauseSuggestResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    suggestions: list[dict[str, Any]] | None = Field(None, title='Suggestions')
    status: str = Field(..., title='Status')


class ClauseUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=255) | None = Field(
        None, description='New name', title='Name'
    )
    content: constr(min_length=1) | None = Field(
        None, description='New content', title='Content'
    )
    category: constr(max_length=100) | None = Field(
        None, description='New category', title='Category'
    )
    tags: list[str] | None = Field(None, description='New tags', title='Tags')
    metadata: dict[str, Any] | None = Field(
        None, description='New metadata', title='Metadata'
    )


class CommencementExtractRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(
        ...,
        description='Gazette text containing commencement notifications',
        title='Text',
    )


class CommencementInstrument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., title='Title')
    commencement_date: str = Field(
        ..., description='ISO 8601 date', title='Commencement Date'
    )
    relevant_sections: list[str] | None = Field(
        None,
        description='Sections prefixed with + (commenced) or - (excluded)',
        title='Relevant Sections',
    )


class ConnectionItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    legisId: str = Field(..., title='Legisid')
    title: str | None = Field(None, title='Title')
    relationship: str | None = Field(None, title='Relationship')


class DocumentCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, title='Title')
    briefcase_id: str | None = Field(None, title='Briefcase Id')
    document_type: str | None = Field(None, title='Document Type')
    content: dict[str, Any] = Field(..., title='Content')
    source_workflow: str = Field(..., title='Source Workflow')
    source_file_id: str | None = Field(None, title='Source File Id')
    job_id: str | None = Field(None, title='Job Id')
    legal_request_id: str | None = Field(None, title='Legal Request Id')
    prompt: str | None = Field(None, title='Prompt')


class DocumentFacets(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    doc_id: str = Field(..., title='Doc Id')
    facets: dict[str, str] = Field(..., title='Facets')
    cached: bool = Field(
        ..., description='True if facets were retrieved from cache', title='Cached'
    )


class DocumentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    title: str | None = Field(None, title='Title')
    document_type: str | None = Field(None, title='Document Type')
    status: str = Field(..., title='Status')
    briefcase_id: str | None = Field(None, title='Briefcase Id')
    content: dict[str, Any] | None = Field(
        None,
        description='Document content as TipTap/ProseMirror JSON.',
        title='Content',
    )
    source_workflow: str | None = Field(None, title='Source Workflow')
    source_file_id: str | None = Field(None, title='Source File Id')
    job_id: str | None = Field(None, title='Job Id')
    legal_request_id: str | None = Field(None, title='Legal Request Id')
    prompt: str | None = Field(None, title='Prompt')
    error: str | None = Field(None, title='Error')
    requires_review: bool | None = Field(False, title='Requires Review')
    reviewed_at: AwareDatetime | None = Field(None, title='Reviewed At')
    reviewed_by: str | None = Field(None, title='Reviewed By')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class DocumentUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, title='Title')
    content: dict[str, Any] | None = Field(None, title='Content')


class DraftRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    prompt: constr(min_length=1) = Field(
        ..., description='Instructions for what to draft.', title='Prompt'
    )
    context: dict[str, Any] | None = Field(
        None,
        description="Optional context for drafting. Common keys: 'briefcase_id' (str), 'jurisdiction' (str), 'style' (str), 'reference_documents' (list[str]). All keys are optional.",
        title='Context',
    )
    document_type: str | None = Field(
        '', description="Type of document (e.g. 'NDA', 'lease')", title='Document Type'
    )
    drafting_style: str | None = Field(
        '',
        description="Style preference (e.g. 'formal', 'plain_english')",
        title='Drafting Style',
    )
    parties: list[dict[str, Any]] | None = Field(
        None, description='Party details: [{name, role, jurisdiction}]', title='Parties'
    )
    document_terms: dict[str, Any] | None = Field(
        None,
        description='Key terms to include (e.g. {term_years: 5})',
        title='Document Terms',
    )
    rag_questions: list[str] | None = Field(
        None,
        description='RAG retrieval questions to inform the draft',
        title='Rag Questions',
    )
    compressed_references: list[str] | None = Field(
        None,
        description='Compressed reference document summaries',
        title='Compressed References',
    )
    model: str | None = Field('', description='Optional model override', title='Model')
    publish_formats: list[str] | None = Field(
        None,
        description="Export formats to generate (e.g. ['docx', 'pdf']). Empty = markdown only.",
        title='Publish Formats',
    )


class DraftResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    draft: str = Field(..., title='Draft')
    warnings: list[str] | None = Field(None, title='Warnings')


class EdiscoveryEmailItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str = Field(..., title='Address')
    context: str = Field(..., title='Context')
    role: str | None = Field(None, title='Role')


class EdiscoveryEmailsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    emails: list[EdiscoveryEmailItem] | None = Field(None, title='Emails')
    status: str = Field(..., title='Status')
    warnings: list[str] | None = Field(None, title='Warnings')


class EdiscoveryEntity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., title='Name')
    type: str = Field(
        ...,
        description='person, organisation, location, court, legislation, date, monetary_amount',
        title='Type',
    )
    context: str = Field(..., title='Context')


class EdiscoveryExtractRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(
        ..., description='Document text to extract from', title='Text'
    )


class EdiscoveryPhoneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    number: str = Field(..., title='Number')
    context: str = Field(..., title='Context')
    type: str | None = Field(None, title='Type')


class EdiscoveryPhonesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phones: list[EdiscoveryPhoneItem] | None = Field(None, title='Phones')
    status: str = Field(..., title='Status')
    warnings: list[str] | None = Field(None, title='Warnings')


class EdiscoverySalientPoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str = Field(..., title='Text')
    category: str = Field(..., title='Category')
    relevance: str = Field(..., title='Relevance')


class EdiscoverySalientResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    points: list[EdiscoverySalientPoint] | None = Field(None, title='Points')
    status: str = Field(..., title='Status')
    warnings: list[str] | None = Field(None, title='Warnings')


class EdiscoveryTextResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str = Field(..., title='Text')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    status: str = Field(..., title='Status')
    warnings: list[str] | None = Field(None, title='Warnings')


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')


class ExtractRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(..., title='Text')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class Status(StrEnum):
    ok = 'ok'
    error = 'error'


class ExtractResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status | None = Field('ok', title='Status')
    kind: str = Field(..., title='Kind')
    extracted: dict[str, Any] | None = Field(None, title='Extracted')
    warnings: list[str] | None = Field(None, title='Warnings')


class FeedbackRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    thumbs_up: bool = Field(..., title='Thumbs Up')
    comment: str | None = Field('', title='Comment')


class FileConfirmRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_id: constr(min_length=1) = Field(..., title='File Id')


class FileDownloadResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    download_url: str = Field(..., title='Download Url')


class FileMetadataResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    filename: str = Field(..., title='Filename')
    content_type: str | None = Field(None, title='Content Type')
    size_bytes: int | None = Field(None, title='Size Bytes')
    status: str = Field(..., title='Status')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class FilePresignRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filename: constr(min_length=1) = Field(..., title='Filename')
    content_type: str | None = Field(None, title='Content Type')


class FilePresignResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_id: str = Field(..., title='File Id')
    upload_url: str = Field(..., title='Upload Url')
    gcs_path: str = Field(..., title='Gcs Path')


class GraphBatchQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legis_id: str = Field(..., title='Legis Id')
    direction: str | None = Field(
        'both', description='inbound, outbound, or both', title='Direction'
    )


class GraphReferenceItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legis_id: str = Field(..., title='Legis Id')
    title: str | None = Field('', title='Title')
    citation: str | None = Field(None, title='Citation')
    country: str | None = Field(None, title='Country')
    url: str | None = Field(None, title='Url')
    type: str | None = Field('', title='Type')


class GraphReferencesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legis_id: str = Field(..., title='Legis Id')
    inbound: list[GraphReferenceItem] | None = Field(None, title='Inbound')
    outbound: list[GraphReferenceItem] | None = Field(None, title='Outbound')
    references: list[GraphReferenceItem] | None = Field(None, title='References')


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str = Field(..., title='Status')


class JobCreatedResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    job_id: str = Field(..., title='Job Id')
    status: Literal['queued'] = Field('queued', title='Status')
    poll_url: str = Field(..., title='Poll Url')


class JobPayload(BaseModel):
    job_id: str = Field(..., title='Job Id')


class Status1(StrEnum):
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class JobResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    type: str = Field(..., title='Type')
    status: Status1 = Field(..., title='Status')
    query: str | None = Field(None, title='Query')
    created_at: AwareDatetime = Field(..., title='Created At')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    completed_at: AwareDatetime | None = Field(None, title='Completed At')
    error: str | None = Field(None, title='Error')


class JobResultResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    status: Status1 = Field(..., title='Status')
    result: dict[str, Any] | None = Field(
        None,
        description='Shape depends on job type. draft: {draft: str, warnings: list[str]}. review: {summary: str, issues: list[ReviewIssue]}. research: {report: str, sources: list}. process: {process_map: str, bottlenecks: list, recommendations: list}. mammoth: {result: str, steps_taken: list[str]}. translate: {translated_text: str}. citation_check: {results: list, total: int, verified: int, hallucinated: int, uncertain: int}.',
        title='Result',
    )


class JokeResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    joke: str = Field(..., title='Joke')
    status: str = Field(..., title='Status')


class LegalConnectionsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inbound: list[ConnectionItem] | None = Field(None, title='Inbound')
    outbound: list[ConnectionItem] | None = Field(None, title='Outbound')
    next_cursor: str | None = Field(None, title='Next Cursor')


class LegalDocumentStatus(StrEnum):
    current = 'current'
    repealed = 'repealed'
    amended = 'amended'
    superseded = 'superseded'


class LegalRequestActivityEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: AwareDatetime = Field(..., title='Timestamp')
    user_id: str | None = Field(None, title='User Id')
    action: str = Field(..., title='Action')
    detail: dict[str, Any] | None = Field(None, title='Detail')


class LegalRequestActivityResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activity: list[LegalRequestActivityEntry] | None = Field(None, title='Activity')


class LegalRequestAssignRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignee_id: constr(min_length=1) = Field(..., title='Assignee Id')
    reason: str | None = Field(None, title='Reason')


class LegalRequestAttachRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_id: constr(min_length=1) = Field(..., title='File Id')


class LegalRequestAttachmentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    request_id: str = Field(..., title='Request Id')
    file_id: str = Field(..., title='File Id')
    filename: str = Field(..., title='Filename')
    content_type: str | None = Field(None, title='Content Type')
    size_bytes: int | None = Field(None, title='Size Bytes')
    attached_by: str = Field(..., title='Attached By')
    created_at: AwareDatetime = Field(..., title='Created At')


class LegalRequestCommentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: constr(min_length=1) = Field(..., title='Content')


class LegalRequestCommentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    request_id: str = Field(..., title='Request Id')
    author_id: str = Field(..., title='Author Id')
    content: str = Field(..., title='Content')
    created_at: AwareDatetime = Field(..., title='Created At')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class LegalRequestCompleteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    result: dict[str, Any] = Field(..., title='Result')


class LegalRequestExecuteResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    status: str = Field(..., title='Status')
    job_id: str = Field(..., title='Job Id')
    poll_url: str = Field(..., title='Poll Url')


class LegalRequestFailRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: constr(min_length=1) = Field(..., title='Error')


class LegalRequestPriority(StrEnum):
    low = 'low'
    normal = 'normal'
    high = 'high'
    urgent = 'urgent'


class LegalRequestResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    org_id: str = Field(..., title='Org Id')
    briefcase_id: str | None = Field(None, title='Briefcase Id')
    requestor_id: str = Field(..., title='Requestor Id')
    assignee_id: str | None = Field(None, title='Assignee Id')
    request_type: str = Field(..., title='Request Type')
    status: str = Field(..., title='Status')
    priority: str = Field(..., title='Priority')
    title: str = Field(..., title='Title')
    description: str | None = Field(None, title='Description')
    category: str | None = Field(None, title='Category')
    input: dict[str, Any] | None = Field(None, title='Input')
    result: dict[str, Any] | None = Field(None, title='Result')
    error: str | None = Field(None, title='Error')
    due_at: AwareDatetime | None = Field(None, title='Due At')
    created_at: AwareDatetime = Field(..., title='Created At')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    completed_at: AwareDatetime | None = Field(None, title='Completed At')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class LegalRequestStatsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    counts: dict[str, int] | None = Field(None, title='Counts')
    total: int | None = Field(0, title='Total')


class LegalRequestStepResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int = Field(..., title='Id')
    step_order: int = Field(..., title='Step Order')
    step_name: str = Field(..., title='Step Name')
    service: str = Field(..., title='Service')
    status: str = Field(..., title='Status')
    input_summary: dict[str, Any] | None = Field(None, title='Input Summary')
    output_summary: dict[str, Any] | None = Field(None, title='Output Summary')
    error: str | None = Field(None, title='Error')
    duration_ms: int | None = Field(None, title='Duration Ms')
    created_at: AwareDatetime = Field(..., title='Created At')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    completed_at: AwareDatetime | None = Field(None, title='Completed At')


class LegalRequestStepsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    steps: list[LegalRequestStepResponse] | None = Field(None, title='Steps')


class LegalRequestType(StrEnum):
    research = 'research'
    draft = 'draft'
    review = 'review'
    extraction = 'extraction'
    analysis = 'analysis'


class LegalRequestUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field(None, title='Title')
    description: str | None = Field(None, title='Description')
    category: str | None = Field(None, title='Category')
    priority: LegalRequestPriority | None = None
    due_at: AwareDatetime | None = Field(None, title='Due At')


class LegalSearchFilters(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    court: list[str] | None = Field(
        None, description='Court names to filter by', title='Court'
    )
    year_from: conint(ge=1900, le=2100) | None = Field(
        None, description='Start year (inclusive)', title='Year From'
    )
    year_to: conint(ge=1900, le=2100) | None = Field(
        None, description='End year (inclusive)', title='Year To'
    )
    legis_type: list[str] | None = Field(
        None,
        description='Legislation types (Act, Regulation, etc.)',
        title='Legis Type',
    )
    legis_status: list[str] | None = Field(
        None,
        description='Legislation status (Current, Repealed, etc.)',
        title='Legis Status',
    )
    source: list[str] | None = Field(
        None, description='News source filter', title='Source'
    )
    author: list[str] | None = Field(
        None, description='News author filter', title='Author'
    )
    agency: list[str] | None = Field(
        None, description='Regulatory agency filter', title='Agency'
    )
    mp_names: list[str] | None = Field(
        None, description='Hansard speaker names', title='Mp Names'
    )
    report_type: list[str] | None = Field(
        None, description='Hansard report type', title='Report Type'
    )


class LegalSearchHit(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    field_index: str | None = Field(None, alias='_index', title='Index')
    field_id: str | None = Field(None, alias='_id', title='Id')
    field_score: float | None = Field(None, alias='_score', title='Score')
    field_source: dict[str, Any] | None = Field(None, alias='_source', title='Source')


class LegalSearchHits(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    total: dict[str, Any] | None = Field(None, title='Total')
    hits: list[LegalSearchHit] | None = Field(None, title='Hits')


class Sort(StrEnum):
    relevance = 'relevance'
    date_desc = 'date_desc'
    date_asc = 'date_asc'


class LegalSearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(
        ..., description='Search query text', title='Query'
    )
    country: str | None = Field(
        None,
        description='ISO country code: SG, UK, AU, MY, ID. Selects indices for that jurisdiction.',
        title='Country',
    )
    indices: list[str] | None = Field(
        None,
        description='Specific ES indices to search (overrides country). For power users.',
        title='Indices',
    )
    size: conint(ge=1, le=100) | None = Field(
        20, description='Number of results to return', title='Size'
    )
    sort: Sort | None = Field(
        'relevance', description='Sort order for results', title='Sort'
    )
    cursor: list[Any] | None = Field(
        None,
        description='Pagination cursor (search_after values from previous response)',
        title='Cursor',
    )
    include_aggregations: bool | None = Field(
        False,
        description='Include facet aggregations in response',
        title='Include Aggregations',
    )
    collapse_duplicates: bool | None = Field(
        True, description='Deduplicate results by legisId', title='Collapse Duplicates'
    )
    filters: LegalSearchFilters | None = Field(
        None, description='Optional filters to narrow results'
    )
    rerank: bool | None = Field(
        True,
        description='Apply Cohere reranking to improve result relevance',
        title='Rerank',
    )
    rerank_top_n: conint(ge=1, le=50) | None = Field(
        20,
        description='Number of results to return after reranking',
        title='Rerank Top N',
    )


class LegalSearchResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    hits: LegalSearchHits | None = None
    query_type: str | None = Field(
        None, description='Set by /search/auto only', title='Query Type'
    )


class MammothRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request: constr(min_length=1) = Field(
        ...,
        description='Natural language request for the orchestrator.',
        title='Request',
    )
    context: dict[str, Any] | None = Field(
        None,
        description="Optional context for orchestration. Common keys: 'user_id' (str), 'jurisdiction' (str), 'document_text' (str). All keys are optional.",
        title='Context',
    )


class MammothResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    result: str = Field(..., description='Orchestrator output', title='Result')
    steps_taken: list[str] | None = Field(
        None, description='Tools/steps used', title='Steps Taken'
    )


class MeOrg(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')
    account_type: str = Field(..., title='Account Type')


class MePreferences(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data_training_opt_out: bool | None = Field(False, title='Data Training Opt Out')


class MeUser(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    email: str = Field(..., title='Email')
    name: str = Field(..., title='Name')
    role: str | None = Field(None, title='Role')
    org_role: str | None = Field(None, title='Org Role')


class MemoryCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: constr(min_length=1, max_length=255) = Field(
        ..., description='Memory key (unique per user)', title='Key'
    )
    content: constr(min_length=1) = Field(
        ..., description='Memory content', title='Content'
    )
    metadata: dict[str, Any] | None = Field(
        None, description='Optional metadata', title='Metadata'
    )


class MemoryResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    content: str = Field(..., title='Content')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class MemorySummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., title='Summary')
    memory_count: int = Field(..., title='Memory Count')
    memories: list[MemoryResponse] = Field(..., title='Memories')


class MemorySynthesiseResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., title='Summary')
    status: str = Field(..., title='Status')


class MemoryUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: constr(min_length=1) | None = Field(
        None, description='New content', title='Content'
    )
    metadata: dict[str, Any] | None = Field(
        None, description='New metadata', title='Metadata'
    )


class ModelInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    provider: str = Field(..., title='Provider')
    name: str = Field(..., title='Name')
    default: bool | None = Field(False, title='Default')


class ModelListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    models: list[ModelInfo] | None = Field(None, title='Models')


class ModelPerformanceResultsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[dict[str, Any]] | None = Field(None, title='Results')


class ModelPerformanceRunResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: str = Field(..., title='Run Id')
    status: str = Field(..., title='Status')


class NotificationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    type: str = Field(..., title='Type')
    title: str = Field(..., title='Title')
    body: str | None = Field(None, title='Body')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    read: bool | None = Field(False, title='Read')
    created_at: AwareDatetime | None = Field(None, title='Created At')


class NotificationSendRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    recipient_id: constr(min_length=1) = Field(
        ..., description='Target user ID (must be in same org)', title='Recipient Id'
    )
    type: constr(min_length=1, max_length=100) = Field(
        ..., description='Notification type', title='Type'
    )
    title: constr(min_length=1, max_length=500) = Field(
        ..., description='Notification title', title='Title'
    )
    body: str | None = Field(None, description='Optional body text', title='Body')
    metadata: dict[str, Any] | None = Field(
        None, description='Optional metadata', title='Metadata'
    )


class OkResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['ok'] = Field('ok', title='Status')


class OrchestrateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ask: constr(min_length=1) = Field(
        ..., description="The user's natural language request.", title='Ask'
    )
    context: dict[str, Any] | None = Field(
        None,
        description="Optional context for orchestration. Common keys: 'briefcase_id' (str), 'chat_id' (str), 'jurisdiction' (str), 'document_text' (str), 'prior_response' (str). All keys are optional.",
        title='Context',
    )


class Kind(StrEnum):
    draft = 'draft'
    review = 'review'
    research = 'research'
    translate = 'translate'
    other = 'other'


class OrchestrateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind | None = Field('other', title='Kind')
    output: dict[str, Any] | None = Field(
        None,
        description='Shape depends on `kind`. draft: DraftResponse fields. review: ReviewResponse fields. research: ResearchResultResponse fields. translate: TranslateResponse fields. other: {status: str}.',
        title='Output',
    )


class OrgInvitationResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    org_id: str = Field(..., title='Org Id')
    inviter_id: str = Field(..., title='Inviter Id')
    invitee_email: str = Field(..., title='Invitee Email')
    role: str = Field(..., title='Role')
    accepted_at: AwareDatetime | None = Field(None, title='Accepted At')
    revoked_at: AwareDatetime | None = Field(None, title='Revoked At')
    created_at: AwareDatetime = Field(..., title='Created At')


class OrgInviteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: constr(min_length=1) = Field(..., title='Email')
    role: str | None = Field('member', title='Role')


class PatchPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: dict[str, Any] | None = Field(None, title='Data')


class PlaybookCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=255) = Field(
        ..., description='Playbook name', title='Name'
    )
    description: str | None = Field(
        None, description='Playbook description', title='Description'
    )
    steps: dict[str, Any] | None = Field(
        None, description='Playbook steps as JSON', title='Steps'
    )
    is_public: bool | None = Field(
        False, description='Whether playbook is publicly visible', title='Is Public'
    )


class PlaybookGenerateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(
        ..., description='Document content to extract rules from', title='Text'
    )
    instructions: str | None = Field(
        None, description='Optional guidance', title='Instructions'
    )
    model: str | None = Field(None, title='Model')


class PlaybookResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    steps: dict[str, Any] | None = Field(None, title='Steps')
    is_public: bool | None = Field(False, title='Is Public')
    created_by: str | None = Field(None, title='Created By')
    created_at: AwareDatetime | None = Field(None, title='Created At')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class PlaybookResynthesiseRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    instructions: str | None = Field(
        None, description='Optional guidance for regeneration', title='Instructions'
    )
    model: str | None = Field(None, title='Model')


class PlaybookRulesRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rule: constr(min_length=1) = Field(
        ..., description='The rule to synthesise and add', title='Rule'
    )
    context: str | None = Field(None, description='Optional context', title='Context')
    model: str | None = Field(None, title='Model')


class PlaybookUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1, max_length=255) | None = Field(
        None, description='New name', title='Name'
    )
    description: str | None = Field(
        None, description='New description', title='Description'
    )
    steps: dict[str, Any] | None = Field(None, description='New steps', title='Steps')
    is_public: bool | None = Field(
        None, description='New public visibility', title='Is Public'
    )


class OverallGrade(StrEnum):
    fail = 'fail'
    weak = 'weak'
    adequate = 'adequate'
    good = 'good'
    very_good = 'very_good'
    excellent = 'excellent'


class PracticeSubmission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    submission: constr(min_length=1) = Field(
        ..., description='The work being submitted for feedback.', title='Submission'
    )
    task_description: constr(min_length=1) = Field(
        ...,
        description="What the submitter was asked to do (e.g. 'Draft a non-compete clause for Singapore').",
        title='Task Description',
    )
    level: str | None = Field(
        'intermediate',
        description="Submitter's level for rubric calibration (e.g. 'student', '3_PQE', 'senior').",
        title='Level',
    )


class ProcessRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: constr(min_length=1) = Field(
        ...,
        description='Description of the process to design or optimize.',
        title='Description',
    )
    context: dict[str, Any] | None = Field(
        None,
        description="Optional context for process design. Common keys: 'current_steps' (list[str]), 'constraints' (list[str]), 'optimization_goals' (list[str]). All keys are optional.",
        title='Context',
    )


class ProcessResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    process_map: str = Field(
        ..., description='Mermaid diagram of the process', title='Process Map'
    )
    bottlenecks: list[str] | None = Field(None, title='Bottlenecks')
    recommendations: list[str] | None = Field(None, title='Recommendations')


class PromptTypeItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: str = Field(..., title='Value')
    description: str = Field(..., title='Description')


class PromptTypesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    prompt_types: list[PromptTypeItem] = Field(..., title='Prompt Types')


class ProximitySearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    term1: constr(min_length=1) = Field(
        ..., description='First term or phrase', title='Term1'
    )
    term2: constr(min_length=1) = Field(
        ..., description='Second term or phrase', title='Term2'
    )
    slop: conint(ge=1, le=100) | None = Field(
        5, description='Maximum word distance between terms', title='Slop'
    )
    in_order: bool | None = Field(
        False,
        description='If true, terms must appear in specified order',
        title='In Order',
    )
    country: str | None = Field(
        None, description='ISO country code: SG, UK, AU, MY, ID', title='Country'
    )
    indices: list[str] | None = Field(
        None, description='Specific ES indices (overrides country)', title='Indices'
    )
    size: conint(ge=1, le=100) | None = Field(
        20, description='Number of results to return', title='Size'
    )
    filters: LegalSearchFilters | None = Field(None, description='Optional filters')
    rerank: bool | None = Field(
        True,
        description='Apply Cohere reranking to improve result relevance',
        title='Rerank',
    )
    rerank_top_n: conint(ge=1, le=50) | None = Field(
        20,
        description='Number of results to return after reranking',
        title='Rerank Top N',
    )


class QueryType(StrEnum):
    keyword = 'keyword'
    semantic = 'semantic'
    boolean = 'boolean'
    proximity = 'proximity'
    hybrid = 'hybrid'


class QueryTypeResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query_type: QueryType = Field(
        ...,
        description='Detected optimal search type for the query',
        title='Query Type',
    )


class ReadyResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str = Field(..., title='Status')
    checks: dict[str, str] | None = Field(None, title='Checks')


class RecentFeedItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    legisId: str = Field(..., title='Legisid')
    title: str | None = Field(None, title='Title')
    enacted_date: date_aliased | None = Field(None, title='Enacted Date')
    indexed_date: AwareDatetime | None = Field(None, title='Indexed Date')
    jurisdiction: str | None = Field(None, title='Jurisdiction')
    doc_type: str | None = Field(None, title='Doc Type')


class RelatedDocument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = Field('', title='Title')
    legisId: str | None = Field('', title='Legisid')
    citation: str | None = Field('', title='Citation')
    url: str | None = Field('', title='Url')
    text_snippet: str | None = Field('', title='Text Snippet')


class ReorderRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    order: list[str] | None = Field(
        None, description='Ordered list of IDs.', title='Order'
    )


class ResearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    question: constr(min_length=1) = Field(
        ..., description='The legal research question.', title='Question'
    )
    constraints: dict[str, Any] | None = Field(
        None,
        description="Optional constraints for research. Common keys: 'jurisdiction' (str), 'year_from' (int), 'year_to' (int), 'sources' (list[str]: 'cases'|'legislation'|'secondary'), 'max_depth' (int). All keys are optional.",
        title='Constraints',
    )
    max_sections: conint(ge=1, le=20) | None = Field(
        None, description='Maximum number of report sections', title='Max Sections'
    )
    publish_formats: list[str] | None = Field(
        None,
        description="Export formats to generate (e.g. ['docx', 'pdf']). Empty = markdown only.",
        title='Publish Formats',
    )
    model: str | None = Field('', description='Optional model override', title='Model')
    guidelines: str | None = Field(
        '',
        description='Additional research guidelines or focus areas',
        title='Guidelines',
    )
    primary_source: str | None = Field(
        '',
        description="Preferred primary source type (e.g. 'cases', 'legislation')",
        title='Primary Source',
    )


class ResearchResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    report_id: str = Field(..., title='Report Id')
    status: Status1 | None = Field('queued', title='Status')


class Kind1(StrEnum):
    risk = 'risk'
    ambiguity = 'ambiguity'
    missing = 'missing'
    style = 'style'
    other = 'other'


class ReviewIssue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind1 | None = Field('other', title='Kind')
    message: str = Field(..., title='Message')
    location: str | None = Field(None, title='Location')
    suggestion: str | None = Field(None, title='Suggestion')


class ReviewRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(
        ..., description='The legal text to review.', title='Text'
    )
    instructions: str | None = Field(
        None,
        description='Optional specific instructions for the review focus.',
        title='Instructions',
    )
    context: dict[str, Any] | None = Field(
        None,
        description="Optional context for review. Common keys: 'jurisdiction' (str), 'document_type' (str), 'playbook_id' (str), 'risk_tolerance' (str: 'low'|'medium'|'high'). All keys are optional.",
        title='Context',
    )


class ReviewResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., title='Summary')
    issues: list[ReviewIssue] | None = Field(None, title='Issues')


class Grade(StrEnum):
    fail = 'fail'
    weak = 'weak'
    adequate = 'adequate'
    good = 'good'
    very_good = 'very_good'
    excellent = 'excellent'


class RubricDimension(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., title='Name')
    grade: Grade = Field(..., title='Grade')
    comment: str = Field(..., title='Comment')


class SearchCiteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legisId: constr(min_length=1) = Field(
        ...,
        description='The legisId of the document to find citing documents for.',
        title='Legisid',
    )


class SearchCiteResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[CitingDocument] | None = Field(None, title='Results')


class SearchGenericResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: str | None = Field(None, title='Query')
    results: list[dict[str, Any]] | None = Field(None, title='Results')
    status: Literal['placeholder'] = Field('placeholder', title='Status')


class SearchItemHighlight(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: list[str] | None = Field(None, title='Title')
    body: list[str] | None = Field(None, title='Body')


class SearchItemSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str | None = Field('', title='Url')
    body: str | None = Field('', title='Body')
    title: str | None = Field('', title='Title')
    date: str | None = Field('', title='Date')
    tags: list[str] | None = Field(None, title='Tags')
    counsel: list[str] | None = Field(None, title='Counsel')
    coram_structured: list[list[str]] | None = Field(None, title='Coram Structured')
    legis_status: str | None = Field(None, title='Legis Status')
    mp_names: list[str | list[str]] | None = Field(None, title='Mp Names')


class SearchQueryRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(..., title='Query')
    limit: conint(ge=1, le=50) | None = Field(10, title='Limit')


class SearchRelateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legis_id: str | None = Field(
        None,
        description='The legisId of the document to find related documents for.',
        title='Legis Id',
    )
    embedding: list[float] | None = Field(
        None,
        description='Alternatively, provide an embedding vector directly.',
        title='Embedding',
    )


class SearchRelateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[RelatedDocument] | None = Field(None, title='Results')


class SearchSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., title='Name')
    url: str = Field(..., title='Url')


class SearchSuggestionsRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(
        ..., description="The user's original query.", title='Query'
    )


class SearchSuggestionsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query_suggestions: list[str] | None = Field(
        None,
        description='List of 5 alternative query phrasings for semantic search.',
        title='Query Suggestions',
    )


class ShareRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sharee_id: str = Field(
        ..., description='User ID to share the briefcase with', title='Sharee Id'
    )
    permission: str | None = Field(
        'read',
        description="Permission level: 'read' or 'read_write'",
        title='Permission',
    )


class SharedBriefcaseItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    share_id: str = Field(..., title='Share Id')
    briefcase_id: str = Field(..., title='Briefcase Id')
    briefcase_name: str = Field(..., title='Briefcase Name')
    sharer_id: str = Field(..., title='Sharer Id')
    permission: str = Field(..., title='Permission')
    accepted_at: str | None = Field(None, title='Accepted At')
    created_at: str = Field(..., title='Created At')


class SharedWithMeResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    briefcases: list[SharedBriefcaseItem] = Field(..., title='Briefcases')
    permissions: list[str] | None = Field(
        None, description='Permission strings (TBD).', title='Permissions'
    )


class StreamFormat(StrEnum):
    type_value = 'type_value'
    results_cherry = 'results_cherry'


class Style(StrEnum):
    brief = 'brief'
    standard = 'standard'
    detailed = 'detailed'


class SummariseChatRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    messages: list[dict[str, Any]] | None = Field(
        None,
        description='List of chat message objects; exact shape TBD.',
        title='Messages',
    )
    style: Style | None = Field('standard', title='Style')


class SummariseChatResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., title='Summary')
    key_points: list[str] | None = Field(None, title='Key Points')


class SummariseDocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(..., title='Text')
    style: Style | None = Field('standard', title='Style')


class SummariseDocumentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., title='Summary')
    key_points: list[str] | None = Field(None, title='Key Points')


class SummariseSearchResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    summary: str = Field(..., title='Summary')
    key_points: list[str] | None = Field(None, title='Key Points')
    citations: list[str] | None = Field(None, title='Citations')


class SummaryComplexity(StrEnum):
    layperson = 'layperson'
    familiar = 'familiar'
    lawyer = 'lawyer'


class SummaryPromptType(StrEnum):
    summary = 'summary'
    principles = 'principles'
    themes = 'themes'
    policy_issue_timeline = 'policy_issue_timeline'
    legislative_timeline = 'legislative_timeline'
    sentencing = 'sentencing'


class TimelineEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    versioned_id: str = Field(
        ..., description='Versioned legisId', title='Versioned Id'
    )
    effective_date: date_aliased = Field(..., title='Effective Date')
    end_date: date_aliased | None = Field(None, title='End Date')
    status: LegalDocumentStatus | None = None


class TranslateChunkedRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(..., title='Text')
    target_lang: constr(min_length=2) = Field(
        ..., description="BCP-47-ish, e.g. 'es', 'fr', 'zh'", title='Target Lang'
    )
    chunk_size_chars: conint(ge=500, le=20000) | None = Field(
        4000, description='Approx chunk size for batching.', title='Chunk Size Chars'
    )
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class Status5(StrEnum):
    ok = 'ok'
    placeholder = 'placeholder'


class TranslateChunkedResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status5 | None = Field('placeholder', title='Status')
    translated_text: str = Field(..., title='Translated Text')
    chunks_used: int = Field(..., title='Chunks Used')


class TranslateDocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(
        ..., description='Document text to translate', title='Text'
    )
    source_language: constr(min_length=2) = Field(
        ...,
        description="BCP-47 source language code (e.g. 'id', 'zh', 'ms')",
        title='Source Language',
    )
    model: str | None = Field('', description='Optional model override', title='Model')


class TranslateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1) = Field(..., title='Text')
    target_lang: constr(min_length=2) = Field(
        ..., description="BCP-47-ish, e.g. 'es', 'fr', 'zh'", title='Target Lang'
    )


class TranslateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    translated_text: str = Field(..., title='Translated Text')


class UnifiedSearchItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    index: str = Field(..., title='Index')
    type: str = Field(..., title='Type')
    source: SearchItemSource
    highlight: SearchItemHighlight


class UnifiedSearchMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    total: int | None = Field(0, title='Total')
    has_next: bool | None = Field(False, title='Has Next')
    next_cursor: list[Any] | None = Field(None, title='Next Cursor')
    query_type: str | None = Field(None, title='Query Type')


class Mode(StrEnum):
    auto = 'auto'
    keyword = 'keyword'
    semantic = 'semantic'
    boolean = 'boolean'


class UnifiedSearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(..., title='Query')
    region: str | None = Field(
        None,
        description='ISO country code: SG, UK, AU, MY, ID. Selects indices for that jurisdiction.',
        title='Region',
    )
    indexes: list[str] | None = Field(
        None, description='Explicit ES indices (overrides region).', title='Indexes'
    )
    mode: Mode | None = Field(
        'auto', description="Search mode. 'auto' detects from query.", title='Mode'
    )
    filters: LegalSearchFilters | None = None
    sort: Sort | None = Field('relevance', title='Sort')
    size: conint(ge=1, le=100) | None = Field(20, title='Size')
    cursor: list[Any] | None = Field(
        None,
        description='search_after values from previous response for pagination.',
        title='Cursor',
    )
    rerank: bool | None = Field(True, title='Rerank')
    rerank_top_n: conint(ge=1, le=50) | None = Field(20, title='Rerank Top N')


class UnifiedSearchResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[UnifiedSearchItem] | None = Field(None, title='Items')
    aggregations: dict[str, list[AggregationBucket]] | None = Field(
        None, title='Aggregations'
    )
    meta: UnifiedSearchMeta | None = None


class UsageResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    org_id: str = Field(..., title='Org Id')
    period: str = Field(..., title='Period')
    metrics: dict[str, int] = Field(..., title='Metrics')


class UserCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str = Field(
        ...,
        description="Always 'error' — users are created via BetterAuth",
        title='Status',
    )
    detail: str | None = Field('Users are created via BetterAuth', title='Detail')


class UserDetailResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    email: str = Field(..., title='Email')
    name: str = Field(..., title='Name')
    org_id: str = Field(..., title='Org Id')
    role: str | None = Field(None, title='Role')
    is_active: bool = Field(..., title='Is Active')
    banned: bool | None = Field(None, title='Banned')


class UserListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    users: list[UserDetailResponse] = Field(..., title='Users')
    count: int = Field(..., title='Count')


class UserPreferencesRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data_training_opt_out: bool | None = Field(None, title='Data Training Opt Out')


class UserPreferencesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data_training_opt_out: bool = Field(..., title='Data Training Opt Out')


class UserPrivilegesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    privileges: list[str] | None = Field(None, title='Privileges')


class UserUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, title='Name')
    role: str | None = Field(None, title='Role')
    banned: bool | None = Field(None, title='Banned')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class WebSearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(..., title='Query')
    allowed_domains: list[str] | None = Field(
        None, description='Restrict results to these domains.', title='Allowed Domains'
    )


class WebSearchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., title='Title')
    url: str = Field(..., title='Url')
    body: str = Field(..., title='Body')


class WebhookCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_type: str = Field(
        ...,
        description='Event type to subscribe to',
        examples=['job.completed', 'job.failed'],
        title='Event Type',
    )
    target_url: AnyUrl = Field(
        ..., description='URL to POST events to', title='Target Url'
    )


class WebhookCreateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    secret: str = Field(
        ..., description='HMAC signing secret (shown only once)', title='Secret'
    )


class WebhookResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    event_type: str = Field(..., title='Event Type')
    target_url: str = Field(..., title='Target Url')
    active: bool = Field(..., title='Active')
    created_at: str = Field(..., title='Created At')


class WhoamiResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_id: str = Field(..., title='User Id')
    org_id: str = Field(..., title='Org Id')


class ElefantApiApiV1InternalPipelinesMemoryExtractResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    processed: int = Field(..., title='Processed')


class ElefantApiApiSchemasMemoryExtractResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    extracted: list[dict[str, Any]] | None = Field(None, title='Extracted')
    status: str = Field(..., title='Status')


class SummaryQuestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['question'] = Field(..., title='Type')
    value: str = Field(..., title='Value')


class SummaryAnswerChunk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['answer'] = Field(..., title='Type')
    value: str = Field(..., title='Value')


class SummaryCitation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    citation: str = Field(..., title='Citation')
    title: str = Field(..., title='Title')
    url: str = Field(..., title='Url')


class SummaryCitations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['citations'] = Field(..., title='Type')
    value: list[SummaryCitation] = Field(..., title='Value')


class SummaryDone(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['done'] = Field(..., title='Type')
    value: str = Field(..., title='Value')


class SummaryError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error'] = Field(..., title='Type')
    value: str = Field(..., title='Value')


class ChatStreamDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['delta'] = Field(..., title='Type')
    value: str = Field(..., title='Value')


class ChatStreamStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['status'] = Field(..., title='Type')
    value: str = Field(..., title='Value')


class ChatStreamDone(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['done'] = Field(..., title='Type')
    value: str = Field(..., title='Value')


class ChatStreamError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error'] = Field(..., title='Type')
    value: str = Field(..., title='Value')


class BriefcaseItemBatchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[BriefcaseItemCreateRequest] = Field(
        ..., max_length=500, min_length=1, title='Items'
    )


class BriefcaseItemListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[BriefcaseItemResponse] | None = Field(None, title='Items')


class BriefcaseItemNoteListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    notes: list[BriefcaseItemNoteResponse] | None = Field(None, title='Notes')


class BriefcaseListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    briefcases: list[BriefcaseResponse] | None = Field(None, title='Briefcases')


class BriefcaseNoteListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    notes: list[BriefcaseNoteResponse] | None = Field(None, title='Notes')


class BriefcaseShareListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    shares: list[BriefcaseShareResponse] = Field(..., title='Shares')


class BriefcaseSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    summaries: list[DocumentFacets] = Field(..., title='Summaries')
    generated_count: int = Field(
        ...,
        description='Number of facets generated (not from cache)',
        title='Generated Count',
    )
    cached_count: int = Field(
        ..., description='Number of facets retrieved from cache', title='Cached Count'
    )


class ChatListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chats: list[ChatSummary] | None = Field(None, title='Chats')


class CitationResultItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    citation: str = Field(..., description='Original citation text', title='Citation')
    status: CitationStatus
    confidence: confloat(ge=0.0, le=1.0) = Field(
        ..., description='Confidence 0.0–1.0', title='Confidence'
    )
    normalized: str | None = Field(
        None, description='Normalized form', title='Normalized'
    )
    source: str = Field(
        ..., description='How verified: known_db, elasticsearch, llm', title='Source'
    )
    reasoning: str | None = Field(
        None, description='LLM reasoning (if LLM-verified)', title='Reasoning'
    )


class ClauseDatabaseListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    databases: list[ClauseDatabaseResponse] | None = Field(None, title='Databases')


class ClauseListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clauses: list[ClauseResponse] | None = Field(None, title='Clauses')


class CommencementExtractResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str = Field(..., title='Status')
    commencements: list[CommencementInstrument] | None = Field(
        None, title='Commencements'
    )
    warnings: list[str] | None = Field(None, title='Warnings')


class DocumentListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documents: list[DocumentResponse] | None = Field(None, title='Documents')


class EdiscoveryEntitiesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entities: list[EdiscoveryEntity] | None = Field(None, title='Entities')
    status: str = Field(..., title='Status')
    warnings: list[str] | None = Field(None, title='Warnings')


class FileListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files: list[FileMetadataResponse] | None = Field(None, title='Files')


class GraphBatchBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    queries: list[GraphBatchQuery] | None = Field(None, title='Queries')


class GraphBatchResultItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legis_id: str = Field(..., title='Legis Id')
    inbound: list[GraphReferenceItem] | None = Field(None, title='Inbound')
    outbound: list[GraphReferenceItem] | None = Field(None, title='Outbound')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class JobListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    jobs: list[JobResponse] | None = Field(None, title='Jobs')


class LegalDocument(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    legisId: str = Field(..., title='Legisid')
    title: str | None = Field(None, title='Title')
    status: LegalDocumentStatus | None = None
    effective_date: date_aliased | None = Field(None, title='Effective Date')
    expiration_date: date_aliased | None = Field(None, title='Expiration Date')
    jurisdiction: str | None = Field(None, title='Jurisdiction')
    doc_type: str | None = Field(None, title='Doc Type')
    instrument_type: str | None = Field(None, title='Instrument Type')
    language: str | None = Field(None, title='Language')
    content: str | None = Field(None, title='Content')
    provisions: list[dict[str, Any]] | None = Field(None, title='Provisions')


class LegalDocumentMetadata(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    legisId: str = Field(..., title='Legisid')
    title: str | None = Field(None, title='Title')
    status: LegalDocumentStatus | None = None
    effective_date: date_aliased | None = Field(None, title='Effective Date')
    expiration_date: date_aliased | None = Field(None, title='Expiration Date')
    jurisdiction: str | None = Field(None, title='Jurisdiction')
    doc_type: str | None = Field(None, title='Doc Type')
    instrument_type: str | None = Field(None, title='Instrument Type')
    language: str | None = Field(None, title='Language')


class LegalRecentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[RecentFeedItem] | None = Field(None, title='Results')
    next_cursor: str | None = Field(None, title='Next Cursor')
    total: int | None = Field(0, title='Total')


class LegalRequestAttachmentListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachments: list[LegalRequestAttachmentResponse] | None = Field(
        None, title='Attachments'
    )


class LegalRequestCommentListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comments: list[LegalRequestCommentResponse] | None = Field(None, title='Comments')


class LegalRequestCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_type: LegalRequestType
    title: constr(min_length=1) = Field(..., title='Title')
    description: str | None = Field(None, title='Description')
    category: str | None = Field(None, title='Category')
    priority: LegalRequestPriority | None = 'normal'
    briefcase_id: str | None = Field(None, title='Briefcase Id')
    input: dict[str, Any] | None = Field(None, title='Input')
    due_at: AwareDatetime | None = Field(None, title='Due At')
    assignee_id: str | None = Field(None, title='Assignee Id')
    as_draft: bool | None = Field(False, title='As Draft')


class LegalRequestListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requests: list[LegalRequestResponse] | None = Field(None, title='Requests')
    total: int | None = Field(0, title='Total')


class LegalTimelineResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legis_id: str = Field(..., title='Legis Id')
    timeline: list[TimelineEntry] | None = Field(None, title='Timeline')


class MeResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user: MeUser
    org: MeOrg
    entitlements: dict[str, Any] = Field(..., title='Entitlements')
    preferences: MePreferences | None = Field(
        default_factory=lambda: MePreferences.model_validate(
            {'data_training_opt_out': False}
        )
    )


class MemoryListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    memories: list[MemoryResponse] | None = Field(None, title='Memories')


class NotificationListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    notifications: list[NotificationResponse] | None = Field(
        None, title='Notifications'
    )
    unread_count: int | None = Field(0, title='Unread Count')


class OrgInvitationListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    invitations: list[OrgInvitationResponse] | None = Field(None, title='Invitations')


class PlaybookListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    playbooks: list[PlaybookResponse] | None = Field(None, title='Playbooks')


class PracticeFeedbackResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_type: str = Field(..., title='Practice Type')
    dimensions: list[RubricDimension] = Field(..., title='Dimensions')
    overall_grade: OverallGrade = Field(..., title='Overall Grade')
    overall_comment: str = Field(..., title='Overall Comment')
    suggestions: list[str] | None = Field(None, title='Suggestions')


class SearchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    title: str = Field(..., title='Title')
    url: str | None = Field(None, title='Url')
    snippet: str | None = Field(None, title='Snippet')
    source: SearchSource | None = None
    score: float | None = Field(None, title='Score')
    published_at: AwareDatetime | None = Field(None, title='Published At')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class SearchSummaryRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    json_response: dict[str, Any] | str = Field(
        ...,
        description='Search results payload. Typically a JSON dict (e.g. Elasticsearch response). If `compressed=true`, this may be a gzip+base64 string.',
        title='Json Response',
    )
    query: constr(min_length=1) = Field(
        ..., description='The original user query.', title='Query'
    )
    prompt_type: SummaryPromptType | None = Field(
        'summary',
        description='Controls the summary style. See `GET /search/summary/prompt-types` for value descriptions.',
    )
    complexity: SummaryComplexity | None = Field(
        'familiar',
        description="Audience complexity level. Controls tone and technical depth. 'layperson' = warm/jargon-free, 'familiar' = professional, 'lawyer' = formal/precise.",
    )
    compressed: bool | None = Field(
        None,
        description='Set true if `json_response` is a gzip+base64 encoded string.',
        title='Compressed',
    )
    stream_format: StreamFormat | None = Field(
        'type_value',
        description="Output format for streaming events. 'type_value' = {type, value} (better for codegen). 'results_cherry' = legacy {context}/{question}/{answer} style.",
    )


class SummariseSearchRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(..., title='Query')
    results: list[SearchResult] = Field(..., title='Results')
    style: Style | None = Field('standard', title='Style')


class WebSearchResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[WebSearchResult] | None = Field(None, title='Results')
    status: str = Field(..., title='Status')


class WebhookListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    webhooks: list[WebhookResponse] = Field(..., title='Webhooks')


class CitationCheckResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[CitationResultItem] = Field(..., title='Results')
    total: int = Field(..., title='Total')
    verified: int = Field(..., title='Verified')
    hallucinated: int = Field(..., title='Hallucinated')
    uncertain: int = Field(..., title='Uncertain')


class GraphBatchResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[GraphBatchResultItem] | None = Field(None, title='Results')


class ResearchResultResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    report_id: str = Field(..., title='Report Id')
    status: Status1 = Field(..., title='Status')
    result: str | None = Field(None, title='Result')
    sources: list[SearchResult] | None = Field(None, title='Sources')
