// ABOUTME: shared mock backend client for rumble front-end.
// ABOUTME: documents expectations for real invoke handlers and provides stubs.
import { ref } from "vue";

export type BackendStatus = "idle" | "running" | "ready" | "error";

export type ReviewSummary = {
  sessionId: string;
  summary: string;
  generatedAt: string;
};

export type ChatMessage = {
  id: string;
  role: "assistant" | "user";
  content: string;
  timestamp: string;
  citations?: string[];
};

export type ReviewSessionResponse = {
  sessionId: string;
  messages: ChatMessage[];
  summary: string;
};

export type ResearchResponse = {
  threadId: string;
  answer: string;
  citations: string[];
};

export type TranslationJobResponse = {
  jobId: string;
  translatedText: string;
};

export type EvalsRunResponse = {
  benchmarkId: string;
  status: "queued" | "completed";
  startedAt: string;
};

export type ProviderSecretPayload = {
  providerId: string;
  label: string;
  scope: "global" | "drafting" | "research";
  notes?: string;
};

export type ApiSurfaceDocumentation = {
  command: string;
  description: string;
  expectedPayload: Record<string, unknown>;
  notes: string;
};

export const backendRegistry = ref<ApiSurfaceDocumentation[]>([
  {
    command: "documents/register_files",
    description: "Register uploaded documents for review.",
    expectedPayload: {
      files: [
        {
          id: "string uuid",
          name: "string",
          sizeBytes: "number",
          customPrompt: "string | null",
        },
      ],
    },
    notes:
      "Backend should persist metadata per session, queue initial analysis, and respond with session identifiers.",
  },
  {
    command: "documents/initial_review",
    description: "Trigger initial outline for a session and return summary + opening assistant message.",
    expectedPayload: { sessionId: "string uuid" },
    notes:
      "Response should include summary text, citations, and any structured issue list. Use streaming if available.",
  },
  {
    command: "documents/chat",
    description: "Send a follow-up question for a session and return assistant reply with citations.",
    expectedPayload: { sessionId: "string uuid", question: "string" },
    notes:
      "Expect streaming partials; front-end currently assumes full response. Include citations as array of strings referencing document + page.",
  },
  {
    command: "research/run_query",
    description: "Kick off a research plan for a thread.",
    expectedPayload: { threadId: "string uuid", prompt: "string", model: "string" },
    notes: "Return instructions and citations. Should persist to allow resume.",
  },
  {
    command: "translation/run",
    description: "Translate text from source to target language.",
    expectedPayload: {
      sourceLanguage: "string",
      targetLanguage: "string",
      text: "string",
      model: "string",
    },
    notes: "Return translated string and quality/confidence metadata.",
  },
  {
    command: "evals/run",
    description: "Queue a benchmark evaluation.",
    expectedPayload: { benchmarkKey: "string", modelIds: ["string"], weightings: "Record<string, number>" },
    notes: "Respond with queued status and benchmark id. Progress should be subscribable.",
  },
  {
    command: "settings/save",
    description: "Persist provider secrets and local configuration.",
    expectedPayload: {
      secrets: [
        {
          provider: "string",
          encryptedKey: "string | null",
          scope: "global | drafting | research",
          notes: "string",
        },
      ],
      local: {
        host: "string",
        port: "string",
        model: "string",
      },
    },
    notes:
      "Backend stores secrets using SQLCipher or OS keychain. Provide validation errors if provider requires key but missing.",
  },
  {
    command: "sync/test",
    description: "Ping sync server health endpoint.",
    expectedPayload: { url: "string" },
    notes: "Respond with status ok/failed and optional diagnostic message.",
  },
]);

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export async function mockRegisterReview(files: { id: string; name: string; sizeBytes: number; customPrompt?: string | null }[]): Promise<ReviewSummary[]> {
  await delay(250);
  return files.map((file) => ({
    sessionId: file.id,
    summary: `Initial review queued for ${file.name}. Prompt: ${file.customPrompt ?? "none provided"}.`,
    generatedAt: new Date().toISOString(),
  }));
}

export async function mockInitialReview(sessionId: string): Promise<ReviewSessionResponse> {
  await delay(300);
  return {
    sessionId,
    summary:
      "Summary generated by mock backend. Replace with backend outline including key obligations, deadlines, and risk items.",
    messages: [
      {
        id: "msg-" + sessionId,
        role: "assistant",
        content: "This is a stubbed initial response. Backend should supply structured bullet points with citations.",
        timestamp: new Date().toISOString(),
        citations: ["Document.pdf · Section 1"],
      },
    ],
  };
}

export async function mockDocumentChat(_sessionId: string, question: string): Promise<ChatMessage> {
  await delay(220);
  return {
    id: `resp-${Date.now()}`,
    role: "assistant",
    content: `Placeholder answer for "${question}". Backend must cite documents using consistent format.`,
    timestamp: new Date().toISOString(),
  };
}

export async function mockResearchRun(threadId: string, prompt: string): Promise<ResearchResponse> {
  await delay(400);
  return {
    threadId,
    answer: `Stub research memo for prompt: ${prompt}. Expect backend to provide structured findings and citations.`,
    citations: ["Case v. Case (2021)", "Statute §123"],
  };
}

export async function mockTranslationRun(payload: {
  sourceLanguage: string;
  targetLanguage: string;
  text: string;
  model: string;
}): Promise<TranslationJobResponse> {
  await delay(200);
  return {
    jobId: `job-${Date.now()}`,
    translatedText: `[Mock translation ${payload.sourceLanguage}→${payload.targetLanguage}] ${payload.text}`,
  };
}

export async function mockEvalsRun(_benchmarkKey: string, _models: string[]): Promise<EvalsRunResponse> {
  await delay(500);
  return {
    benchmarkId: `benchmark-${Date.now()}`,
    status: "completed",
    startedAt: new Date().toISOString(),
  };
}

export async function mockSaveSettings(): Promise<void> {
  await delay(150);
}

export async function mockTestSync(url: string): Promise<{ ok: boolean; message?: string }> {
  await delay(180);
  return {
    ok: true,
    message: `Mocked connection successful to ${url}`,
  };
}
