/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Breakdown of users by signup method.

`manual` is the count of accounts with provider_id = 'credential'.
WS-16 deepdive amendment: previous FE implementation derived this as
`total - google - microsoft`, which double-subtracts users with
multiple linked providers. PR-31 fixes this here — BE becomes the
source of truth.
 */
export interface AdminDashboardByMethod {
  /** @minimum 0 */
  google: number;
  /** @minimum 0 */
  microsoft: number;
  /** @minimum 0 */
  manual: number;
}
