/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { AdminDashboardSearchCounts } from './adminDashboardSearchCounts';
import type { AdminDashboardUserCounts } from './adminDashboardUserCounts';

/**
 * Platform-wide aggregate stats for the admin dashboard.

Shape mirrors `frontend/apps/nuxt/server/api/v1/admin/dashboard/stats.get.ts`
so PR-32 is a drop-in proxy rewrite. Cross-tenant by definition; routed
through `get_admin_session` (BYPASSRLS).
 */
export interface AdminDashboardStatsResponse {
  users: AdminDashboardUserCounts;
  searches: AdminDashboardSearchCounts;
  /** @minimum 0 */
  briefcasesTotal: number;
  /** @minimum 0 */
  chatsTotal: number;
  /** @minimum 0 */
  llmTokensLifetime: number;
  /** @minimum 0 */
  monthlyActiveOrgs: number;
  timestamp: string;
}
