/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { AdminAuditLogEntryDetails } from './adminAuditLogEntryDetails';

/**
 * One row from web.audit_log (the FE-owned platform-admin audit table).

Distinct from `AuditLogEntry` in `internal_schemas.py`, which models
public.audit_log (org-scoped tenant events). See WS-16 deepdive Q2:
these are genuinely separate physical tables.
 */
export interface AdminAuditLogEntry {
  id: string;
  adminId?: string | null;
  adminEmail?: string | null;
  targetUserId?: string | null;
  action: string;
  details?: AdminAuditLogEntryDetails;
  ipAddress?: string | null;
  createdAt: string;
}
