/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { AdminDashboardByMethod } from './adminDashboardByMethod';

export interface AdminDashboardUserCounts {
  /** @minimum 0 */
  total: number;
  /** @minimum 0 */
  today: number;
  /** @minimum 0 */
  yesterday: number;
  /** @minimum 0 */
  thisWeek: number;
  /** @minimum 0 */
  thisMonth: number;
  /** @minimum 0 */
  verified: number;
  /** @minimum 0 */
  unverified: number;
  growthRate: number;
  byMethod: AdminDashboardByMethod;
}
