/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { AdminAuditLogEntry } from './adminAuditLogEntry';

/**
 * Paginated platform-admin audit log listing.

Page-based pagination mirrors the FE shape so PR-32 stays a drop-in.
Internally the query uses keyset on `(created_at, id) DESC` per PR-24
keyset standard — `page`/`totalPages` are derived from `total` + `limit`.
 */
export interface AdminAuditLogsResponse {
  logs?: AdminAuditLogEntry[];
  /** @minimum 0 */
  total: number;
  /** @minimum 1 */
  page: number;
  /** @minimum 0 */
  totalPages: number;
}
