/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Detail for an 'assigned' action: manual assignment to a specific user.
 */
export interface AssignedDetail {
  assignedTo: string;
  reason?: string | null;
}
