/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A user who can be assigned to legal requests.
 */
export interface AssignableUserResponse {
  id: string;
  name: string;
  email: string;
  org_role?: string | null;
}
