/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { CasesSource } from './casesSource';

export interface AuCasesHit {
  _id?: string | null;
  _score?: number | null;
  _index: 'search-au_cases';
  _source: CasesSource;
}
