/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { PlanPrice } from './planPrice';

/**
 * Per-plan live prices. Plans with no configured/retrievable Stripe Price
are omitted; the FE falls back to its hardcoded constant for those.
 */
export interface BillingPricesResponse {
  prices: PlanPrice[];
}
