/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to invalidate cached summaries.
 */
export interface BriefcaseInvalidateRequest {
  /**
     * Legal document IDs to invalidate
     * @minItems 1
     * @maxItems 50
     */
  doc_ids: string[];
}
