/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { BriefcaseWithNotesItem } from './briefcaseWithNotesItem';

/**
 * Manifest+notes export data — read by the FE renderer in PR-32.

Supports three FE export modes:
  - manifest: titles + legis_ids only (NEW in PR-31, served from same body)
  - notes:    titles + body + per-item notes (existing)
  - combined: union of the above

The BE returns the full payload; mode selection is FE-side rendering.
 */
export interface BriefcaseWithNotesResponse {
  briefcaseId: string;
  name: string;
  createdAt: string;
  /** @minimum 0 */
  itemCount: number;
  items?: BriefcaseWithNotesItem[];
}
