/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export interface BriefcaseResponse {
  id: string;
  name: string;
  active?: boolean;
  pinned?: boolean;
  position?: number | null;
  created_at?: string | null;
  updated_at?: string | null;
}
