/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentFacets } from './documentFacets.ts';

/**
 * Response containing generated/cached summaries.
 */
export interface BriefcaseSummaryResponse {
  summaries: DocumentFacets[];
  /** Number of facets generated (not from cache) */
  generated_count: number;
  /** Number of facets retrieved from cache */
  cached_count: number;
}
