/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * A per-item note, slimmed to the fields FE export consumers use.

Field names match the FE export contract (`noteId`, `text`, `createdAt`),
not the underlying DB columns. The mapping is done in the route handler.
 */
export interface BriefcaseItemNoteSummary {
  noteId: string;
  text: string;
  createdAt: string;
}
