/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export interface BriefcaseNoteRequest {
  /** Optional note title */
  title?: string | null;
  /**
   * Note body text
   * @minLength 1
   */
  body: string;
}
