/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { BriefcaseItemCreateRequest } from './briefcaseItemCreateRequest';

export interface BriefcaseItemBatchRequest {
  /**
   * @minItems 1
   * @maxItems 500
   */
  items: BriefcaseItemCreateRequest[];
}
