/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { BriefcaseItemNoteSummary } from './briefcaseItemNoteSummary';

/**
 * A briefcase item enriched with notes and a resolved ES title.

`title` is best-effort: when ES is unavailable or returns no hit for an
item's `legis_id`, this falls back to the cached `briefcase_item.title`
column, then to None — never raises. See BE-3 handler comments.
 */
export interface BriefcaseWithNotesItem {
  briefcaseItemId: string;
  legisId: string;
  title?: string | null;
  url?: string | null;
  body?: string | null;
  notes?: BriefcaseItemNoteSummary[];
}
