/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export interface BriefcaseItemResponse {
  id: string;
  briefcaseId: string;
  legisId: string;
  title?: string | null;
  url?: string | null;
  body?: string | null;
  type?: string | null;
  tags?: string[];
  timestamp?: number | null;
  position?: number;
  addedAt?: string | null;
}
