/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export interface BriefcaseItemCreateRequest {
  /**
   * Legal resource ID to add
   * @minLength 1
   */
  legis_id: string;
  /** Optional display title */
  title?: string | null;
  /** Optional URL */
  url?: string | null;
  /** Optional body text / content snippet */
  body?: string | null;
  /** Optional item type (e.g. legislation, case) */
  type?: string | null;
  /** Category tags */
  tags?: string[];
  /** Unix ms timestamp for sorting */
  timestamp?: number | null;
}
