/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { DocumentFacets } from './documentFacets';

/**
 * Response containing generated/cached summaries.
 */
export interface BriefcaseSummaryResponse {
  summaries: DocumentFacets[];
  /** Number of facets generated (not from cache) */
  generatedCount: number;
  /** Number of facets retrieved from cache */
  cachedCount: number;
}
