/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export interface BriefcaseUpdateRequest {
  /** New name */
  name?: string | null;
  /** Pin briefcase to top */
  pinned?: boolean | null;
  /** Whether briefcase is active */
  active?: boolean | null;
}
