/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Request to pre-generate summaries for legal documents.
 */
export interface BriefcaseSummarizeRequest {
  /**
   * Legal document IDs (legisIds) to summarize
   * @minItems 1
   * @maxItems 50
   */
  doc_ids: string[];
  /** Facets to generate: overview, key_provisions, scope, risks, definitions, procedural, penalties */
  facets?: string[];
}
