/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export interface BriefcaseShareResponse {
  id: string;
  briefcaseId: string;
  sharerId: string;
  shareeId: string;
  permission: string;
  acceptedAt?: string | null;
  revokedAt?: string | null;
  createdAt: string;
}
