/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { CasesSourceCoramStructured } from './casesSourceCoramStructured';

/**
 * Cases indices: SG, UK, AU, HK.
 */
export interface CasesSource {
  url?: string | null;
  sortDate?: number | string | null;
  title?: string | null;
  body?: string | null;
  court?: string | null;
  citation?: string | null;
  counsel?: string | string[] | null;
  coramStructured?: CasesSourceCoramStructured;
}
