/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export interface ChatMessage {
  id: string;
  /** Message role: 'user' or 'assistant'. */
  role: string;
  content: string;
  /** Serialised JSON string of citation sources, if any. */
  sources?: string | null;
  tokenCount?: number | null;
  thumbsUp?: boolean | null;
  createdAt: string;
}
