/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export interface ChatMessageRequest {
  /** @minLength 1 */
  text: string;
  learning_mode?: boolean;
  model?: string;
  /** Legal document IDs (legisIds) to include as RAG context */
  briefcase_doc_ids?: string[] | null;
  /** Specific facets to include: overview, key_provisions, scope, risks, etc. */
  briefcase_facets?: string[] | null;
}
