/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { ChatMessagesResponseMessagesItem } from './chatMessagesResponseMessagesItem.ts';

export interface ChatMessagesResponse {
  chat_id: string;
  /** Array of chat messages. Each item: {role: 'user'|'assistant', content: str, created_at: str, id: str}. */
  messages?: ChatMessagesResponseMessagesItem[];
}
