/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { CitationStatus } from './citationStatus';

/**
 * Verification result for a single citation.
 */
export interface CitationResultItem {
  /** Original citation text */
  citation: string;
  status: CitationStatus;
  /**
   * Confidence 0.0–1.0
   * @minimum 0
   * @maximum 1
   */
  confidence: number;
  /** Normalized form */
  normalized?: string | null;
  /** How verified: known_db, elasticsearch, llm */
  source: string;
  /** LLM reasoning (if LLM-verified) */
  reasoning?: string | null;
}
