/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Verification status for a citation.
 */
export type CitationStatus = typeof CitationStatus[keyof typeof CitationStatus];


export const CitationStatus = {
  verified: 'verified',
  hallucinated: 'hallucinated',
  uncertain: 'uncertain',
} as const;
