/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Input for citation verification (document text or single citation).
 */
export interface CitationCheckRequest {
  /** Document text or single citation to verify */
  text: string;
}
