/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { CitationResultItem } from './citationResultItem.ts';

/**
 * Manifest of citation verification results.
 */
export interface CitationCheckResponse {
  results: CitationResultItem[];
  total: number;
  verified: number;
  hallucinated: number;
  uncertain: number;
}
