/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { CitationCheckResultResultsItem } from './citationCheckResultResultsItem';

/**
 * Result of the `citation_check` job handler.
 */
export interface CitationCheckResult {
  jobType: 'citation_check';
  results?: CitationCheckResultResultsItem[];
  total: number;
  verified?: number;
  hallucinated?: number;
  uncertain?: number;
}
