/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { ClarifyRequestContext } from './clarifyRequestContext';
import type { ClarifyRequestDocumentTerms } from './clarifyRequestDocumentTerms';
import type { ClarifyRequestPartiesItem } from './clarifyRequestPartiesItem';

/**
 * Request to clarify a user's legal question.

The clarify endpoint analyzes the user's ask and returns clarifying questions
to help refine the query before proceeding with research or drafting.
 */
export interface ClarifyRequest {
  /**
   * The user's question or request to clarify.
   * @minLength 1
   */
  ask: string;
  /** Optional context to inform clarification. Common keys: 'jurisdiction' (str), 'document_type' (str), 'briefcase_id' (str), 'prior_messages' (list[str]). All keys are optional. */
  context?: ClarifyRequestContext;
  /** Type of document for context */
  documentType?: string;
  /** Drafting style preference */
  draftingStyle?: string;
  /** Party details for context */
  parties?: ClarifyRequestPartiesItem[];
  /** Key terms for context */
  documentTerms?: ClarifyRequestDocumentTerms;
  /** Compressed reference summaries for context */
  compressedReferences?: string[];
  /** File IDs from /files/presign to use as reference context */
  referenceFileIds?: string[];
}
