/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Optional context to inform clarification. Common keys: 'jurisdiction' (str), 'document_type' (str), 'briefcase_id' (str), 'prior_messages' (list[str]). All keys are optional.
 */
export type ClarifyRequestContext = { [key: string]: unknown };
