/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { ClauseUpdateRequestMetadata } from './clauseUpdateRequestMetadata';

/**
 * Request to update an existing clause.
 */
export interface ClauseUpdateRequest {
  /** New name */
  name?: string | null;
  /** New content */
  content?: string | null;
  /** New category */
  category?: string | null;
  /** New tags */
  tags?: string[] | null;
  /** New metadata */
  metadata?: ClauseUpdateRequestMetadata;
}
