/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { ClauseCreateRequestMetadata } from './clauseCreateRequestMetadata';

/**
 * Request to create a new clause.
 */
export interface ClauseCreateRequest {
  /**
   * Clause name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Clause content/text
   * @minLength 1
   */
  content: string;
  /** Clause category */
  category?: string | null;
  /** Clause tags */
  tags?: string[];
  /** Additional metadata */
  metadata?: ClauseCreateRequestMetadata;
}
