/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Clause database (org's implicit collection) in API response.
 */
export interface ClauseDatabaseResponse {
  /** Database ID (same as org_id) */
  id: string;
  /** Database name */
  name?: string;
  /** Number of clauses in database */
  clause_count?: number;
}
