/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { ClauseResponseMetadata } from './clauseResponseMetadata';

/**
 * Single clause in API response.
 */
export interface ClauseResponse {
  id: string;
  name: string;
  content: string;
  category?: string | null;
  tags?: string[];
  metadata?: ClauseResponseMetadata;
  created_by?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}
