/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { ClauseResponseMetadata } from './clauseResponseMetadata';

/**
 * Single clause in API response.
 */
export interface ClauseResponse {
  id: string;
  name: string;
  content: string;
  category?: string | null;
  tags?: string[];
  metadata?: ClauseResponseMetadata;
  createdBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}
