/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Single connection item.
 */
export interface ConnectionItem {
  legisId: string;
  title?: string | null;
  relationship?: string | null;
}
