/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentCreateRequestContent } from './documentCreateRequestContent.ts';

/**
 * Create a document. Called by backend workflows, not users.
 */
export interface DocumentCreateRequest {
  title?: string | null;
  briefcase_id?: string | null;
  document_type?: string | null;
  content: DocumentCreateRequestContent;
  source_workflow: string;
  source_file_id?: string | null;
  job_id?: string | null;
  legal_request_id?: string | null;
  prompt?: string | null;
}
