/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { DocumentResponseContent } from './documentResponseContent';
import type { DocumentResponseDownloadUrls } from './documentResponseDownloadUrls';

/**
 * Full document representation.
 */
export interface DocumentResponse {
  id: string;
  title?: string | null;
  documentType?: string | null;
  status: string;
  briefcaseId?: string | null;
  /** Document content as TipTap/ProseMirror JSON. */
  content?: DocumentResponseContent;
  sourceWorkflow?: string | null;
  sourceFileId?: string | null;
  jobId?: string | null;
  legalRequestId?: string | null;
  prompt?: string | null;
  error?: string | null;
  requiresReview?: boolean;
  reviewedAt?: string | null;
  reviewedBy?: string | null;
  createdAt: string;
  updatedAt: string;
  /** Per-format presigned download URLs, e.g. {"pdf": "...", "docx": "..."} */
  downloadUrls?: DocumentResponseDownloadUrls;
}
