/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { DocumentUpdateRequestContent } from './documentUpdateRequestContent';

/**
 * Update document content (WYSIWYG edits by user).
 */
export interface DocumentUpdateRequest {
  title?: string | null;
  content?: DocumentUpdateRequestContent;
}
