/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentResponseContent } from './documentResponseContent';

/**
 * Full document representation.
 */
export interface DocumentResponse {
  id: string;
  title?: string | null;
  document_type?: string | null;
  status: string;
  briefcase_id?: string | null;
  /** Document content as TipTap/ProseMirror JSON. */
  content?: DocumentResponseContent;
  source_workflow?: string | null;
  source_file_id?: string | null;
  job_id?: string | null;
  legal_request_id?: string | null;
  prompt?: string | null;
  error?: string | null;
  requires_review?: boolean;
  reviewed_at?: string | null;
  reviewed_by?: string | null;
  created_at: string;
  updated_at: string;
}
