/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { DocumentFacetsFacets } from './documentFacetsFacets';

/**
 * Facets for a single document.
 */
export interface DocumentFacets {
  docId: string;
  facets: DocumentFacetsFacets;
  /** True if facets were retrieved from cache */
  cached: boolean;
}
