/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { DocumentCreateRequestContent } from './documentCreateRequestContent';

/**
 * Create a document. Called by backend workflows, not users.
 */
export interface DocumentCreateRequest {
  title?: string | null;
  briefcaseId?: string | null;
  documentType?: string | null;
  content: DocumentCreateRequestContent;
  sourceWorkflow: string;
  sourceFileId?: string | null;
  jobId?: string | null;
  legalRequestId?: string | null;
  prompt?: string | null;
}
