/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentFacetsFacets } from './documentFacetsFacets.ts';

/**
 * Facets for a single document.
 */
export interface DocumentFacets {
  doc_id: string;
  facets: DocumentFacetsFacets;
  /** True if facets were retrieved from cache */
  cached: boolean;
}
