/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { DraftField } from './draftField.ts';
import type { DraftRequestContext } from './draftRequestContext.ts';
import type { DraftRequestDocumentTerms } from './draftRequestDocumentTerms.ts';
import type { DraftRequestPartiesItem } from './draftRequestPartiesItem.ts';

/**
 * Request to draft legal content based on a prompt.
 */
export interface DraftRequest {
  /**
     * Instructions for what to draft.
     * @minLength 1
     */
  prompt: string;
  /** Optional context for drafting. Common keys: 'briefcase_id' (str), 'jurisdiction' (str), 'style' (str), 'reference_documents' (list[str]). All keys are optional. */
  context?: DraftRequestContext;
  /** Type of document (e.g. 'NDA', 'lease') */
  document_type?: string;
  /** Style preference (e.g. 'formal', 'plain_english') */
  drafting_style?: string;
  /** Party details: [{name, role, jurisdiction}] */
  parties?: DraftRequestPartiesItem[];
  /** Key terms to include (e.g. {term_years: 5}) */
  document_terms?: DraftRequestDocumentTerms;
  /** RAG retrieval questions to inform the draft */
  rag_questions?: string[];
  /** Compressed reference document summaries */
  compressed_references?: string[];
  /** Optional model override */
  model?: string;
  /** Export formats to generate (e.g. ['docx', 'pdf']). Empty = markdown only. */
  publish_formats?: string[];
  /** The template's fields as filled in: key, label, type, value, aliases. Drives placeholder substitution after drafting; absent means no substitution. */
  fields?: DraftField[];
}
