/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One of the template's fields as the user filled it in.
 */
export interface DraftField {
  /** Form field key, e.g. 'employeeName'. */
  key: string;
  /** Human-readable label shown to the user, e.g. 'Employee Name'. */
  label: string;
  /** Field type hint: 'date' for date-typed fields, 'freetext' for open-ended prose fields. Omitted for plain exact-match fields. */
  type?: string;
  /** The value the user entered for this field. */
  value: string;
  /** Alternate labels substitution should also recognise for this field, e.g. ['Role', 'Job Title'] for Position. */
  aliases?: string[];
}
