/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { DraftRequestContext } from './draftRequestContext';
import type { DraftRequestDocumentTerms } from './draftRequestDocumentTerms';
import type { DraftRequestPartiesItem } from './draftRequestPartiesItem';
import type { DraftRequestPublishFormatsItem } from './draftRequestPublishFormatsItem';

/**
 * Request to draft legal content based on a prompt.
 */
export interface DraftRequest {
  /**
   * Instructions for what to draft.
   * @minLength 1
   */
  prompt: string;
  /** Optional context for drafting. Common keys: 'briefcase_id' (str), 'jurisdiction' (str), 'style' (str), 'reference_documents' (list[str]). All keys are optional. */
  context?: DraftRequestContext;
  /** Type of document (e.g. 'NDA', 'lease') */
  documentType?: string;
  /** Style preference (e.g. 'formal', 'plain_english') */
  draftingStyle?: string;
  /** Party details: [{name, role, jurisdiction}] */
  parties?: DraftRequestPartiesItem[];
  /** Key terms to include (e.g. {term_years: 5}) */
  documentTerms?: DraftRequestDocumentTerms;
  /** RAG retrieval questions to inform the draft */
  ragQuestions?: string[];
  /** Compressed reference document summaries */
  compressedReferences?: string[];
  /** File IDs from /files/presign to use as reference context */
  referenceFileIds?: string[];
  /** Optional model override */
  model?: string;
  /** Export formats to generate (e.g. ['docx', 'pdf']). Empty = markdown only. */
  publishFormats?: DraftRequestPublishFormatsItem[];
  /** Playbook ID to use as drafting constraints (requires DRAFTER_PLAYBOOK_ENABLED). */
  playbookId?: string | null;
}
