/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export type DraftRequestPublishFormatsItem = typeof DraftRequestPublishFormatsItem[keyof typeof DraftRequestPublishFormatsItem];


export const DraftRequestPublishFormatsItem = {
  markdown: 'markdown',
  pdf: 'pdf',
  docx: 'docx',
} as const;
