/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { DraftInputTerms } from './draftInputTerms';
import type { Party } from './party';

/**
 * Structured input for a `draft` legal request.
 */
export interface DraftInput {
  type?: 'draft';
  /** @minLength 1 */
  documentType: string;
  parties?: Party[];
  terms?: DraftInputTerms;
  /** Optional playbook (ULID/UUID string) to constrain drafting. */
  playbookId?: string | null;
  referenceFileIds?: string[] | null;
}
