/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional context for drafting. Common keys: 'briefcase_id' (str), 'jurisdiction' (str), 'style' (str), 'reference_documents' (list[str]). All keys are optional.
 */
export type DraftRequestContext = { [key: string]: unknown };
