/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { DraftResultCitationsItem } from './draftResultCitationsItem';

/**
 * Result of the `draft` job handler.
 */
export interface DraftResult {
  jobType: 'draft';
  draft: string;
  citations?: DraftResultCitationsItem[];
  warnings?: string[];
  downloadUrls?: string[];
  version?: number | null;
}
