/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Org-scoped feature entitlements and quota limits.

All values are ints: -1 = unlimited, 0 = disabled, positive = limit.
`has_*` and `admin_model_control` are boolean feature gates encoded as 0/1.
The 47 listed keys mirror `core.plan_defaults`. `extra="allow"` (inherited
from PermissiveResponse) preserves the existing permissive contract where DB
overrides may add unknown keys (see `test_entitlements_parity`), while still
giving the FE typed access to the known keys.
 */
export interface EntitlementsResponse {
  searchWebRequestsMonthly: number;
  searchWebRequestsDaily: number;
  draftRequestsMonthly: number;
  draftRequestsDaily: number;
  reviewRequestsMonthly: number;
  reviewRequestsDaily: number;
  researchRequestsMonthly: number;
  researchRequestsDaily: number;
  translateRequestsMonthly: number;
  translateRequestsDaily: number;
  mcpRequestsMonthly: number;
  mcpRequestsDaily: number;
  chatRequestsMonthly: number;
  chatRequestsDaily: number;
  learnRequestsMonthly: number;
  learnRequestsDaily: number;
  citationChecksMonthly: number;
  citationChecksDaily: number;
  playbookRequestsMonthly: number;
  playbookRequestsDaily: number;
  processRequestsMonthly: number;
  processRequestsDaily: number;
  mammothRequestsMonthly: number;
  mammothRequestsDaily: number;
  orchestrateRequestsMonthly: number;
  orchestrateRequestsDaily: number;
  clarifyRequestsMonthly: number;
  clarifyRequestsDaily: number;
  searchSummaryRequestsMonthly: number;
  searchSummaryRequestsDaily: number;
  searchSuggestionsRequestsMonthly: number;
  searchSuggestionsRequestsDaily: number;
  searchRelateRequestsMonthly: number;
  searchRelateRequestsDaily: number;
  searchCiteRequestsMonthly: number;
  searchCiteRequestsDaily: number;
  chatTitleRequestsMonthly: number;
  chatTitleRequestsDaily: number;
  apiKeyRequestsPerMinute: number;
  maxJurisdictions: number;
  maxBriefcaseSaves: number;
  hasResearchTool: number;
  hasCommercialUse: number;
  hasTeamFeatures: number;
  hasModelChoice: number;
  hasAdFree: number;
  adminModelControl: number;
  [key: string]: unknown;
 }
