/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Structured error response envelope. All BE error bodies use this shape.

Mirrors the FE's ApiErrorEnvelope at apps/nuxt/app/api/unwrap.ts so the
proxy's parseEnvelope() accepts BE-native bodies without normalisation.

Inherits BaseResponse (extra="forbid", populate_by_name=True, from_attributes=True).
Explicit Field(alias=...) on every field overrides the to_camel alias generator,
preserving snake_case wire keys so the FE proxy's normalise-error.ts parses
them correctly without a paired FE change.
 */
export interface ErrorEnvelope {
  error?: true;
  /** HTTP status code */
  upstream_status: number;
  /** Coarse class: ClientError | ServerError | ValidationError | AuthError */
  error_class: string;
  /** Machine-readable error code (e.g. UNAUTHORIZED, VALIDATION_ERROR) */
  code: string;
  /** Human-readable summary */
  message: string;
  /** Optional diagnostic hint for integration partners */
  hint?: string | null;
  path?: string | null;
  detail?: unknown | null;
  retry_after_seconds?: number | null;
  request_id?: string | null;
}
