/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * An external counsel entry in the org rolodex.
 */
export interface ExternalCounselResponse {
  userId: string | null;
  email: string;
  displayName: string;
  firmName: string | null;
  addedBy: string;
  invitePending: boolean;
  createdAt: string;
  updatedAt: string;
}
