/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Request body to invite an external counsel to the org.
 */
export interface ExternalCounselCreateRequest {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  displayName: string;
  firmName?: string | null;
}
