/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractResponseExtracted } from './extractResponseExtracted';
import type { ExtractResponseStatus } from './extractResponseStatus';

export interface ExtractResponse {
  status?: ExtractResponseStatus;
  kind: string;
  extracted?: ExtractResponseExtracted;
  warnings?: string[];
}
