/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Echo of the persisted feedback row so callers can confirm what
landed in the database (which message, which direction) without a
follow-up GET. Replaces the bare OkResponse which lost that info.

Inherits BaseResponse so the wire format is camelCase
(messageId / thumbsUp) per the project-wide invariant.
 */
export interface FeedbackResponse {
  messageId: string;
  thumbsUp: boolean;
}
