/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Full file metadata response.
 */
export interface FileMetadataResponse {
  id: string;
  filename: string;
  content_type?: string | null;
  size_bytes?: number | null;
  status: string;
  created_at: string;
  updated_at: string;
}
