/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Full file metadata response.
 */
export interface FileMetadataResponse {
  /**
   * ULID (26-char Crockford base-32).
   * @pattern ^[0-9A-HJKMNP-TV-Z]{26}$
   */
  id: string;
  filename: string;
  contentType?: string | null;
  sizeBytes?: number | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}
