/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Filename / size metadata travelling alongside a base64-encoded upload.

Defined with the bare BaseModel rather than BaseRequest because the wire
shape here is intentionally snake_case to match what the FE mapper already
produces (see `frontend/apps/nuxt/shared/types/file.ts`).
 */
export interface FileContentBlockMetadataRequest {
  filename: string;
  size: number;
  type: string;
}
