/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { FileContentBlockMetadataRequest } from './fileContentBlockMetadataRequest';

/**
 * One uploaded file, base64-inlined for the chat-stream request.

Mirrors `frontend/apps/nuxt/shared/types/file.ts:FileContentBlockSchema`.
The wire shape is snake_case (`source_type`, `mime_type`); BaseRequest-
style camel aliasing is intentionally not applied here so the FE can post
the exact shape its mapper already produces.

`mime_type` is validated against `_ALLOWED_CHAT_CONTENT_BLOCK_MIME_TYPES`
— a 422 here is much better than a multi-second LLM round-trip that
silently ignores or misinterprets a format the model can't handle.
 */
export interface FileContentBlockRequest {
  type: string;
  source_type: string;
  mime_type: string;
  data: string;
  metadata: FileContentBlockMetadataRequest;
}
