/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Response with presigned upload URL.
 */
export interface FilePresignResponse {
  /**
   * ULID (26-char Crockford base-32).
   * @pattern ^[0-9A-HJKMNP-TV-Z]{26}$
   */
  fileId: string;
  uploadUrl: string;
  gcsPath: string;
}
