/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response with presigned upload URL.
 */
export interface FilePresignResponse {
  file_id: string;
  upload_url: string;
  gcs_path: string;
}
