/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export type GetJobStatusParams = {
/**
 * Optional long-poll seconds (0-30). If the job is not yet completed or failed, the server holds the connection open up to this many seconds and returns immediately on terminal transition. Default 0 preserves the non-blocking single-read behaviour.
 * @minimum 0
 * @maximum 30
 */
wait?: number;
};
