/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { GetLegalConnectionsDirection } from './getLegalConnectionsDirection.ts';

export type GetLegalConnectionsParams = {
direction?: GetLegalConnectionsDirection;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Pagination cursor
 */
cursor?: string | null;
};
