/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export type GetLegalConnectionsDirection = typeof GetLegalConnectionsDirection[keyof typeof GetLegalConnectionsDirection] | null;


export const GetLegalConnectionsDirection = {
  inbound: 'inbound',
  outbound: 'outbound',
} as const;
