/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export type GetLegalDocumentParams = {
/**
 * Point-in-time version
 */
as_of?: string | null;
/**
 * Specific provision ID
 */
provision?: string | null;
/**
 * Return metadata only
 */
fields?: 'metadata' | null;
/**
 * ISO 639-1
 */
language?: string | null;
};
