/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export type GetLegalRecentParams = {
/**
 * Filter by enacted date
 */
since_enacted?: string | null;
/**
 * Filter by indexed date
 */
since_indexed?: string | null;
until_enacted?: string | null;
until_indexed?: string | null;
doc_type?: string | null;
jurisdiction?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string | null;
};
