/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * SG hansard (parliamentary records) index.

reportType and mpNames are camelCase in the ES wire payload, matching
what the alias generator would produce — declared with explicit
Field(alias=...) for clarity.
 */
export interface HansardSource {
  url?: string | null;
  sortDate?: number | string | null;
  title?: string | null;
  body?: string | null;
  reportType?: string | null;
  mpNames?: string[] | null;
}
