/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Short-lived impersonation token (30-min TTL).
 */
export interface ImpersonationResponse {
  /** JWT for impersonating the target user. */
  token: string;
  expiresAt: string;
  targetUserId: string;
  targetOrgId: string;
  impersonatorId: string;
}
