/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Elasticsearch indices available to search.
 */
export type IndexName = typeof IndexName[keyof typeof IndexName];


export const IndexName = {
  'search-sg_cases': 'search-sg_cases',
  'search-sso': 'search-sso',
  'search-hansard': 'search-hansard',
  'search-news': 'search-news',
  'search-sg_reg': 'search-sg_reg',
  'search-uk_cases': 'search-uk_cases',
  'search-uk_legis': 'search-uk_legis',
  'search-au_cases': 'search-au_cases',
  'search-au_legis': 'search-au_legis',
  'search-my_legislation': 'search-my_legislation',
  'search-idn_legislation': 'search-idn_legislation',
  'search-hk_cases': 'search-hk_cases',
  'search-hk_legislation': 'search-hk_legislation',
  'search-ca_legislation': 'search-ca_legislation',
  'search-us_legislation': 'search-us_legislation',
  'search-us_ca_legislation': 'search-us_ca_legislation',
  'search-us_de_legislation': 'search-us_de_legislation',
  'search-us_ma_legislation': 'search-us_ma_legislation',
  'search-us_ny_legislation': 'search-us_ny_legislation',
} as const;
