/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Result of the `ingest_upload` job handler.

Status-driven: 'ingested' | 'already_ingested' | 'skipped'.
Only ingested/already_ingested include document_id.
 */
export interface IngestUploadResult {
  jobType: 'ingest_upload';
  status: string;
  fileId: string;
  documentId?: string | null;
  reason?: string | null;
  charCount?: number | null;
}
