/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response when a job is created and enqueued.
 */
export interface JobCreatedResponse {
  job_id: string;
  status?: 'queued';
  poll_url: string;
}
