/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Shape depends on job type. draft: {draft: str, warnings: list[str]}. review: {summary: str, issues: list[ReviewIssue]}. research: {report: str, sources: list}. process: {process_map: str, bottlenecks: list, recommendations: list}. mammoth: {result: str, steps_taken: list[str]}. translate: {translated_text: str}. citation_check: {results: list, total: int, verified: int, hallucinated: int, uncertain: int}.
 */
export type JobResultResponseResult = { [key: string]: unknown } | null;
