/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { JobProgressInfo } from './jobProgressInfo';
import type { JobResponseStatus } from './jobResponseStatus';

/**
 * Job status response for polling.
 */
export interface JobResponse {
  id: string;
  type: string;
  status: JobResponseStatus;
  query?: string | null;
  progress?: JobProgressInfo | null;
  cancelRequested?: boolean;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  error?: string | null;
}
