/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { JobResponseStatus } from './jobResponseStatus.ts';

/**
 * Job status response for polling.
 */
export interface JobResponse {
  id: string;
  type: string;
  status: JobResponseStatus;
  query?: string | null;
  created_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  error?: string | null;
}
