/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { CitationCheckResult } from './citationCheckResult';
import type { DraftResult } from './draftResult';
import type { IngestUploadResult } from './ingestUploadResult';
import type { JobResultResponseStatus } from './jobResultResponseStatus';
import type { LegalRequestResult } from './legalRequestResult';
import type { MammothResult } from './mammothResult';
import type { PlaybookGenerateResult } from './playbookGenerateResult';
import type { PlaybookResynthesiseResult } from './playbookResynthesiseResult';
import type { PlaybookRulesResult } from './playbookRulesResult';
import type { ProcessResult } from './processResult';
import type { ResearchResult } from './researchResult';
import type { ReviewResult } from './reviewResult';
import type { TranslateResult } from './translateResult';

/**
 * Job result response (includes result payload).
 */
export interface JobResultResponse {
  id: string;
  status: JobResultResponseStatus;
  /** Typed result payload; shape discriminated by job_type. */
  result?: ResearchResult | DraftResult | ReviewResult | ProcessResult | MammothResult | LegalRequestResult | TranslateResult | PlaybookGenerateResult | PlaybookRulesResult | PlaybookResynthesiseResult | IngestUploadResult | CitationCheckResult | null;
}
