/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalRequestCreateRequestInput } from './legalRequestCreateRequestInput';
import type { LegalRequestPriority } from './legalRequestPriority';
import type { LegalRequestType } from './legalRequestType';

/**
 * Create a new legal request.
 */
export interface LegalRequestCreateRequest {
  request_type: LegalRequestType;
  /** @minLength 1 */
  title: string;
  description?: string | null;
  category?: string | null;
  priority?: LegalRequestPriority;
  briefcase_id?: string | null;
  input?: LegalRequestCreateRequestInput;
  due_at?: string | null;
  assignee_id?: string | null;
  as_draft?: boolean;
}
