/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { LegalDocumentProvisions } from './legalDocumentProvisions';
import type { LegalDocumentStatus } from './legalDocumentStatus';

/**
 * Full legal document including content.
 */
export interface LegalDocument {
  legisId: string;
  title?: string | null;
  status?: LegalDocumentStatus | null;
  effectiveDate?: string | null;
  expirationDate?: string | null;
  jurisdiction?: string | null;
  docType?: string | null;
  instrumentType?: string | null;
  language?: string | null;
  content?: string | null;
  provisions?: LegalDocumentProvisions;
}
