/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Sort order for results
 */
export type LegalSearchRequestSort = typeof LegalSearchRequestSort[keyof typeof LegalSearchRequestSort];


export const LegalSearchRequestSort = {
  relevance: 'relevance',
  date_desc: 'date_desc',
  date_asc: 'date_asc',
} as const;
