/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { TimelineEntry } from './timelineEntry';

/**
 * Timeline of all versions of a document.
 */
export interface LegalTimelineResponse {
  legisId: string;
  timeline?: TimelineEntry[];
}
