/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalRequestStatsResponseCounts } from './legalRequestStatsResponseCounts.ts';

/**
 * Counts of legal requests grouped by status.
 */
export interface LegalRequestStatsResponse {
  counts?: LegalRequestStatsResponseCounts;
  total?: number;
}
