/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A comment on a legal request.
 */
export interface LegalRequestCommentResponse {
  id: string;
  request_id: string;
  author_id: string;
  content: string;
  created_at: string;
  updated_at: string;
}
