/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { AnalysisInput } from './analysisInput';
import type { DraftInput } from './draftInput';
import type { ExtractionInput } from './extractionInput';
import type { LegalRequestPriority } from './legalRequestPriority';
import type { LegalRequestResponseResult } from './legalRequestResponseResult';
import type { LegalRequestStatus } from './legalRequestStatus';
import type { LegalRequestType } from './legalRequestType';
import type { ResearchInput } from './researchInput';
import type { ReviewInput } from './reviewInput';
import type { UncertainInput } from './uncertainInput';

/**
 * Full legal request representation.
 */
export interface LegalRequestResponse {
  /**
   * ULID (26-char Crockford base-32).
   * @pattern ^[0-9A-HJKMNP-TV-Z]{26}$
   */
  id: string;
  orgId: string;
  briefcaseId?: string | null;
  requestorId: string;
  assigneeId?: string | null;
  requestType: LegalRequestType;
  status: LegalRequestStatus;
  priority: LegalRequestPriority;
  title: string;
  description?: string | null;
  category?: string | null;
  input?: ResearchInput | DraftInput | ReviewInput | ExtractionInput | AnalysisInput | UncertainInput | null;
  result?: LegalRequestResponseResult;
  error?: string | null;
  dueAt?: string | null;
  restricted?: boolean;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
}
