/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Types of legal requests.
 */
export type LegalRequestType = typeof LegalRequestType[keyof typeof LegalRequestType];


export const LegalRequestType = {
  research: 'research',
  draft: 'draft',
  review: 'review',
  extraction: 'extraction',
  analysis: 'analysis',
} as const;
