/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalRequestActivityEntry } from './legalRequestActivityEntry.ts';

/**
 * Activity feed for a legal request (audit + assignments).
 */
export interface LegalRequestActivityResponse {
  activity?: LegalRequestActivityEntry[];
}
