/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response when a legal request execution job is enqueued.
 */
export interface LegalRequestExecuteResponse {
  id: string;
  status: string;
  job_id: string;
  poll_url: string;
}
