/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { LegalRequestStepResponseInputSummary } from './legalRequestStepResponseInputSummary';
import type { LegalRequestStepResponseOutputSummary } from './legalRequestStepResponseOutputSummary';

/**
 * A single step in legal request processing.
 */
export interface LegalRequestStepResponse {
  id: number;
  stepOrder: number;
  stepName: string;
  service: string;
  status: string;
  inputSummary?: LegalRequestStepResponseInputSummary;
  outputSummary?: LegalRequestStepResponseOutputSummary;
  error?: string | null;
  durationMs?: number | null;
  createdAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
}
