/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalRequestResponseInput } from './legalRequestResponseInput';
import type { LegalRequestResponseResult } from './legalRequestResponseResult';

/**
 * Full legal request representation.
 */
export interface LegalRequestResponse {
  id: string;
  org_id: string;
  briefcase_id?: string | null;
  requestor_id: string;
  assignee_id?: string | null;
  request_type: string;
  status: string;
  priority: string;
  title: string;
  description?: string | null;
  category?: string | null;
  input?: LegalRequestResponseInput;
  result?: LegalRequestResponseResult;
  error?: string | null;
  due_at?: string | null;
  created_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  updated_at: string;
}
