/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { TimelineEntry } from './timelineEntry.ts';

/**
 * Timeline of all versions of a document.
 */
export interface LegalTimelineResponse {
  legis_id: string;
  timeline?: TimelineEntry[];
}
