/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Filters for legal search queries.

All fields are optional. Only provided filters are applied.
 */
export interface LegalSearchFilters {
  /** Court names to filter by */
  court?: string[] | null;
  /** Start year (inclusive) */
  yearFrom?: number | null;
  /** End year (inclusive) */
  yearTo?: number | null;
  /** Legislation types (Act, Regulation, etc.) */
  legisType?: string[] | null;
  /** Legislation status (Current, Repealed, etc.) */
  legisStatus?: string[] | null;
  /** News source filter */
  source?: string[] | null;
  /** News author filter */
  author?: string[] | null;
  /** Regulatory agency filter */
  agency?: string[] | null;
  /** Hansard speaker names */
  mpNames?: string[] | null;
  /** Hansard report type */
  reportType?: string[] | null;
}
