/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * A comment on a legal request.
 */
export interface LegalRequestCommentResponse {
  id: string;
  requestId: string;
  authorId: string;
  content: string;
  createdAt: string;
  updatedAt: string;
}
