/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalRequestStepResponseInputSummary } from './legalRequestStepResponseInputSummary';
import type { LegalRequestStepResponseOutputSummary } from './legalRequestStepResponseOutputSummary';

/**
 * A single step in legal request processing.
 */
export interface LegalRequestStepResponse {
  id: number;
  step_order: number;
  step_name: string;
  service: string;
  status: string;
  input_summary?: LegalRequestStepResponseInputSummary;
  output_summary?: LegalRequestStepResponseOutputSummary;
  error?: string | null;
  duration_ms?: number | null;
  created_at: string;
  started_at?: string | null;
  completed_at?: string | null;
}
