/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Attach a file to a legal request.
 */
export interface LegalRequestAttachRequest {
  /** @minLength 1 */
  fileId: string;
}
