/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Status of a legal document version.
 */
export type LegalDocumentStatus = typeof LegalDocumentStatus[keyof typeof LegalDocumentStatus];


export const LegalDocumentStatus = {
  current: 'current',
  repealed: 'repealed',
  amended: 'amended',
  superseded: 'superseded',
} as const;
