/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalSearchHit } from './legalSearchHit';
import type { LegalSearchHitsTotal } from './legalSearchHitsTotal';

export interface LegalSearchHits {
  total?: LegalSearchHitsTotal;
  hits?: LegalSearchHit[];
  [key: string]: unknown;
 }
