/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Access tier: view (read-only), comment (+attach), full (assignee-equivalent).
 */
export type LegalRequestCollaboratorInviteRequestPermission = typeof LegalRequestCollaboratorInviteRequestPermission[keyof typeof LegalRequestCollaboratorInviteRequestPermission];


export const LegalRequestCollaboratorInviteRequestPermission = {
  view: 'view',
  comment: 'comment',
  full: 'full',
} as const;
