/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A file attachment on a legal request.
 */
export interface LegalRequestAttachmentResponse {
  id: string;
  request_id: string;
  file_id: string;
  filename: string;
  content_type?: string | null;
  size_bytes?: number | null;
  attached_by: string;
  created_at: string;
}
