/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { LegalRequestCollaboratorInviteRequestPermission } from './legalRequestCollaboratorInviteRequestPermission';

/**
 * Invite an external user as a collaborator on a legal request.
 */
export interface LegalRequestCollaboratorInviteRequest {
  /**
   * Target user (cross-org).
   * @minLength 1
   */
  userId: string;
  /** Access tier: view (read-only), comment (+attach), full (assignee-equivalent). */
  permission?: LegalRequestCollaboratorInviteRequestPermission;
}
