/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalSearchFilters } from './legalSearchFilters.ts';
import type { LegalSearchRequestSort } from './legalSearchRequestSort.ts';

/**
 * Request for legal document search.
 *
 * Used by /search/keyword, /search/semantic, /search/boolean, /search/auto endpoints.
 */
export interface LegalSearchRequest {
  /**
     * Search query text
     * @minLength 1
     */
  query: string;
  /** ISO country code: SG, UK, AU, MY, ID. Selects indices for that jurisdiction. */
  country?: string | null;
  /** Specific ES indices to search (overrides country). For power users. */
  indices?: string[] | null;
  /**
     * Number of results to return
     * @minimum 1
     * @maximum 100
     */
  size?: number;
  /** Sort order for results */
  sort?: LegalSearchRequestSort;
  /** Pagination cursor (search_after values from previous response) */
  cursor?: unknown[] | null;
  /** Include facet aggregations in response */
  include_aggregations?: boolean;
  /** Deduplicate results by legisId */
  collapse_duplicates?: boolean;
  /** Optional filters to narrow results */
  filters?: LegalSearchFilters | null;
  /** Apply Cohere reranking to improve result relevance */
  rerank?: boolean;
  /**
     * Number of results to return after reranking
     * @minimum 1
     * @maximum 50
     */
  rerank_top_n?: number;
}
