/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { _LegalSearchHitSource } from './_legalSearchHitSource.ts';

/**
 * Single ES search hit. Uses extra='allow' because ES fields vary by index.
 */
export interface LegalSearchHit {
  _index?: string | null;
  _id?: string | null;
  _score?: number | null;
  _source?: _LegalSearchHitSource;
  [key: string]: unknown;
 }
