/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { IndexName } from './indexName';
import type { LegalSearchFilters } from './legalSearchFilters';
import type { LegalSearchRequestSort } from './legalSearchRequestSort';
import type { SearchRegion } from './searchRegion';

/**
 * Request for legal document search.

Used by /search/keyword, /search/semantic, /search/boolean, /search/auto endpoints.
 */
export interface LegalSearchRequest {
  /**
   * Search query text
   * @minLength 1
   */
  query: string;
  /** ISO jurisdiction code (SG, UK, AU, MY, ID, HK, CA, US, US_CA, US_DE, US_MA, US_NY). Selects indices for that jurisdiction. US_* codes are state-level. */
  country?: SearchRegion | null;
  /** Specific ES indices to search (overrides country). For power users. */
  indices?: IndexName[] | null;
  /**
   * Number of results to return
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Sort order for results */
  sort?: LegalSearchRequestSort;
  /** Pagination cursor (search_after values from previous response) */
  cursor?: unknown[] | null;
  /** Include facet aggregations in response */
  includeAggregations?: boolean;
  /** Deduplicate results by legisId */
  collapseDuplicates?: boolean;
  /** Optional filters to narrow results */
  filters?: LegalSearchFilters | null;
  /** Apply Cohere reranking to improve result relevance */
  rerank?: boolean;
  /**
   * Number of results to return after reranking
   * @minimum 1
   * @maximum 50
   */
  rerankTopN?: number;
}
