/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * A file attachment on a legal request.
 */
export interface LegalRequestAttachmentResponse {
  id: string;
  requestId: string;
  fileId: string;
  filename: string;
  contentType?: string | null;
  sizeBytes?: number | null;
  attachedBy: string;
  createdAt: string;
}
