/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalDocumentStatus } from './legalDocumentStatus.ts';

/**
 * Metadata-only response for a legal document.
 */
export interface LegalDocumentMetadata {
  legisId: string;
  title?: string | null;
  status?: LegalDocumentStatus | null;
  effective_date?: string | null;
  expiration_date?: string | null;
  jurisdiction?: string | null;
  doc_type?: string | null;
  instrument_type?: string | null;
  language?: string | null;
  [key: string]: unknown;
 }
