/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { LegalRequestCycleTime } from './legalRequestCycleTime';
import type { LegalRequestMetricsResponseCompletedByType } from './legalRequestMetricsResponseCompletedByType';
import type { LegalRequestMetricsResponseOpenByStatus } from './legalRequestMetricsResponseOpenByStatus';

/**
 * Org-level Mammoth impact metrics over a rolling window.

Counts-only aggregates, RLS-scoped to the caller's org (no PII). Throughput
and cycle time cover the trailing `window_days`; `open_by_status` is a
current snapshot of the backlog regardless of window.
 */
export interface LegalRequestMetricsResponse {
  windowDays: number;
  created?: number;
  completed?: number;
  completedByType?: LegalRequestMetricsResponseCompletedByType;
  openByStatus?: LegalRequestMetricsResponseOpenByStatus;
  cycleTime?: LegalRequestCycleTime;
  disclaimer?: string;
}
