/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Assign a legal request to a user.
 */
export interface LegalRequestAssignRequest {
  /** @minLength 1 */
  assigneeId: string;
  reason?: string | null;
}
