/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Cycle-time percentiles (hours) over requests completed in the window.

Null when nothing completed in the window — there's no meaningful percentile
of an empty set, and zero would read as "instant", which is misleading.
 */
export interface LegalRequestCycleTime {
  p50Hours?: number | null;
  p90Hours?: number | null;
}
