/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalSearchHits } from './legalSearchHits.ts';

/**
 * Typed wrapper for raw ES search responses. extra='allow' for aggregations etc.
 */
export interface LegalSearchResponse {
  hits?: LegalSearchHits;
  /** Set by /search/auto only */
  query_type?: string | null;
  [key: string]: unknown;
 }
