/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalRequestPriority } from './legalRequestPriority.ts';

/**
 * Update legal request metadata.
 */
export interface LegalRequestUpdateRequest {
  title?: string | null;
  description?: string | null;
  category?: string | null;
  priority?: LegalRequestPriority | null;
  due_at?: string | null;
}
