/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { LegalRequestPriority } from './legalRequestPriority';

/**
 * Update legal request metadata.
 */
export interface LegalRequestUpdateRequest {
  title?: string | null;
  description?: string | null;
  category?: string | null;
  priority?: LegalRequestPriority | null;
  /** Deadline for the request. Accepts an ISO date (`YYYY-MM-DD`) or a full ISO date-time. Date-only values are coerced to 23:59:59 Asia/Singapore (end-of-day local). */
  dueAt?: string | null;
  restricted?: boolean | null;
}
