/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Status of a legal request.
 */
export type LegalRequestStatus = typeof LegalRequestStatus[keyof typeof LegalRequestStatus];


export const LegalRequestStatus = {
  pending: 'pending',
  assigned: 'assigned',
  in_progress: 'in_progress',
  awaiting_review: 'awaiting_review',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;
