/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalDocumentProvisions } from './legalDocumentProvisions.ts';
import type { LegalDocumentStatus } from './legalDocumentStatus.ts';

/**
 * Full legal document including content.
 */
export interface LegalDocument {
  legisId: string;
  title?: string | null;
  status?: LegalDocumentStatus | null;
  effective_date?: string | null;
  expiration_date?: string | null;
  jurisdiction?: string | null;
  doc_type?: string | null;
  instrument_type?: string | null;
  language?: string | null;
  content?: string | null;
  provisions?: LegalDocumentProvisions;
  [key: string]: unknown;
 }
