/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export type ListAdminAuditLogsParams = {
/**
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
/**
 * @minimum 0
 */
skip?: number;
/**
 * Filter by exact action name
 */
action?: string | null;
/**
 * Filter by admin_email (exact match)
 */
adminEmail?: string | null;
/**
 * Inclusive lower bound on created_at (ISO-8601)
 */
startDate?: string | null;
/**
 * Exclusive upper bound on created_at (ISO-8601)
 */
endDate?: string | null;
};
