/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export type ListDocumentsParams = {
briefcase_id?: string | null;
legal_request_id?: string | null;
source_workflow?: string | null;
};
