/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export type ListJobsParams = {
status?: string | null;
type?: string | null;
/**
 * @minimum 1
 * @maximum 50
 */
limit?: number;
cursor?: string | null;
};
