/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional context for orchestration. Common keys: 'user_id' (str), 'jurisdiction' (str), 'document_text' (str). All keys are optional.
 */
export type MammothRequestContext = { [key: string]: unknown };
