/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { MammothRequestContext } from './mammothRequestContext';

/**
 * Request for complex multi-step legal tasks via Mammoth orchestrator.
 */
export interface MammothRequest {
  /**
   * Natural language request for the orchestrator.
   * @minLength 1
   */
  request: string;
  /** Optional context for orchestration. Common keys: 'user_id' (str), 'jurisdiction' (str), 'document_text' (str). All keys are optional. */
  context?: MammothRequestContext;
}
