/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { MemoryResponseMetadata } from './memoryResponseMetadata';

export interface MemoryResponse {
  id: string;
  key: string;
  content: string;
  metadata?: MemoryResponseMetadata;
  createdAt?: string | null;
  updatedAt?: string | null;
}
