/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { MemoryCreateRequestMetadata } from './memoryCreateRequestMetadata';

export interface MemoryCreateRequest {
  /**
   * Memory key (unique per user)
   * @minLength 1
   * @maxLength 255
   */
  key: string;
  /**
   * Memory content
   * @minLength 1
   */
  content: string;
  /** Optional metadata */
  metadata?: MemoryCreateRequestMetadata;
}
