/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { MeOrg } from './meOrg.ts';
import type { MePreferences } from './mePreferences.ts';
import type { MeResponseEntitlements } from './meResponseEntitlements.ts';
import type { MeUser } from './meUser.ts';

export interface MeResponse {
  user: MeUser;
  org: MeOrg;
  entitlements: MeResponseEntitlements;
  preferences?: MePreferences;
}
