/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * SG news index.
 */
export interface NewsSource {
  url?: string | null;
  sortDate?: number | string | null;
  title?: string | null;
  body?: string | null;
  author?: string | null;
  source?: string | null;
}
