/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationResponseMetadata } from './notificationResponseMetadata.ts';

export interface NotificationResponse {
  id: string;
  type: string;
  title: string;
  body?: string | null;
  metadata?: NotificationResponseMetadata;
  read?: boolean;
  created_at?: string | null;
}
