/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { NotificationSendRequestMetadata } from './notificationSendRequestMetadata';

export interface NotificationSendRequest {
  /**
   * Target user ID (must be in same org)
   * @minLength 1
   */
  recipientId: string;
  /**
   * Notification type
   * @minLength 1
   * @maxLength 100
   */
  type: string;
  /**
   * Notification title
   * @minLength 1
   * @maxLength 500
   */
  title: string;
  /** Optional body text */
  body?: string | null;
  /** Optional metadata */
  metadata?: NotificationSendRequestMetadata;
}
