/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Optional context for orchestration. Common keys: 'briefcase_id' (str), 'chat_id' (str), 'jurisdiction' (str), 'document_text' (str), 'prior_response' (str). All keys are optional.
 */
export type OrchestrateRequestContext = { [key: string]: unknown };
