/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export type OrchestrateResponseKind = typeof OrchestrateResponseKind[keyof typeof OrchestrateResponseKind];


export const OrchestrateResponseKind = {
  draft: 'draft',
  review: 'review',
  research: 'research',
  translate: 'translate',
  other: 'other',
} as const;
