/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { OrchestrateRequestContext } from './orchestrateRequestContext';

/**
 * Request for the Mammoth orchestration endpoint.

Mammoth analyzes the user's ask and routes to the appropriate capability
(draft, review, research, translate, etc.).
 */
export interface OrchestrateRequest {
  /**
   * The user's natural language request.
   * @minLength 1
   */
  ask: string;
  /** Optional context for orchestration. Common keys: 'briefcase_id' (str), 'chat_id' (str), 'jurisdiction' (str), 'document_text' (str), 'prior_response' (str). All keys are optional. */
  context?: OrchestrateRequestContext;
}
