/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { OrchestrateResponseKind } from './orchestrateResponseKind';
import type { OrchestrateResponseOutput } from './orchestrateResponseOutput';

export interface OrchestrateResponse {
  kind?: OrchestrateResponseKind;
  /** Shape depends on `kind`. draft: DraftResponse fields. review: ReviewResponse fields. research: ResearchResultResponse fields. translate: TranslateResponse fields. other: {status: str}. */
  output?: OrchestrateResponseOutput;
}
