/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Shape depends on `kind`. draft: DraftResponse fields. review: ReviewResponse fields. research: ResearchResultResponse fields. translate: TranslateResponse fields. other: {status: str}.
 */
export type OrchestrateResponseOutput = { [key: string]: unknown };
