/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * A party to a draft (counterparty / principal / etc).
 */
export interface Party {
  /** @minLength 1 */
  name: string;
  /** Party's role, e.g. 'lessor', 'employer', 'counterparty'. */
  role?: string | null;
  jurisdiction?: string | null;
}
