/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { PatchPayloadData } from './patchPayloadData.ts';

/**
 * Generic patch payload when the exact fields are still evolving.
 */
export interface PatchPayload {
  data?: PatchPayloadData;
}
