/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Detail for a 'picked_up' action: user self-assigned via /pick-up endpoint.
 */
export interface PickedUpDetail {
  assignedTo: string;
}
