/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { PlanPriceInterval } from './planPriceInterval';

/**
 * Live plan price sourced from the configured Stripe Price object.

``amount`` and ``yearly_amount`` are whole dollars (Stripe ``unit_amount`` is
cents; we divide by 100) so the value drops straight into the FE display path
that already uses whole-dollar constants. ``interval`` mirrors the Stripe
recurring interval, with ``"none"`` for the $0 Lite product.
 */
export interface PlanPrice {
  plan: string;
  interval: PlanPriceInterval;
  amount: number;
  currency: string;
  yearlyAmount?: number | null;
}
