/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybookUpdateRequestSteps } from './playbookUpdateRequestSteps';

/**
 * Request to update an existing playbook.
 */
export interface PlaybookUpdateRequest {
  /** New name */
  name?: string | null;
  /** New description */
  description?: string | null;
  /** New steps */
  steps?: PlaybookUpdateRequestSteps;
  /** New public visibility */
  is_public?: boolean | null;
}
