/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export interface PlaybookRulesRequest {
  /**
     * The rule to synthesise and add
     * @minLength 1
     */
  rule: string;
  /** Optional context */
  context?: string | null;
  model?: string | null;
}
