/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybookCreateRequestSteps } from './playbookCreateRequestSteps.ts';

/**
 * Request to create a new playbook.
 */
export interface PlaybookCreateRequest {
  /**
     * Playbook name
     * @minLength 1
     * @maxLength 255
     */
  name: string;
  /** Playbook description */
  description?: string | null;
  /** Playbook steps as JSON */
  steps?: PlaybookCreateRequestSteps;
  /** Whether playbook is publicly visible */
  is_public?: boolean;
}
