/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { PlaybookCreateRequestSteps } from './playbookCreateRequestSteps';

/**
 * Request to create a new playbook.
 */
export interface PlaybookCreateRequest {
  /**
   * Playbook name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** Playbook description */
  description?: string | null;
  /** Playbook steps as JSON */
  steps?: PlaybookCreateRequestSteps;
  /** Whether playbook is publicly visible */
  isPublic?: boolean;
}
