/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { PlaybookResponseSteps } from './playbookResponseSteps';

/**
 * Single playbook in API response.
 */
export interface PlaybookResponse {
  id: string;
  name: string;
  description?: string | null;
  steps?: PlaybookResponseSteps;
  is_public?: boolean;
  created_by?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}
