/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Result of the `playbook_resynthesise` job handler.
 */
export interface PlaybookResynthesiseResult {
  jobType: 'playbook_resynthesise';
  playbookId: string;
  stepCount: number;
}
