/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export interface PracticeSubmission {
  /**
   * The work being submitted for feedback.
   * @minLength 1
   */
  submission: string;
  /**
   * What the submitter was asked to do (e.g. 'Draft a non-compete clause for Singapore').
   * @minLength 1
   */
  taskDescription: string;
  /** Submitter's level for rubric calibration (e.g. 'student', '3_PQE', 'senior'). */
  level?: string;
}
