/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { PracticeFeedbackResponseOverallGrade } from './practiceFeedbackResponseOverallGrade';
import type { RubricDimension } from './rubricDimension';

export interface PracticeFeedbackResponse {
  practice_type: string;
  dimensions: RubricDimension[];
  overall_grade: PracticeFeedbackResponseOverallGrade;
  overall_comment: string;
  suggestions?: string[];
}
