/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export type PracticeFeedbackResponseOverallGrade = typeof PracticeFeedbackResponseOverallGrade[keyof typeof PracticeFeedbackResponseOverallGrade];


export const PracticeFeedbackResponseOverallGrade = {
  fail: 'fail',
  weak: 'weak',
  adequate: 'adequate',
  good: 'good',
  very_good: 'very_good',
  excellent: 'excellent',
} as const;
