/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Response containing the designed process.
 */
export interface ProcessResponse {
  /** Mermaid diagram of the process */
  processMap: string;
  bottlenecks?: string[];
  recommendations?: string[];
}
