/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { ProcessRequestContext } from './processRequestContext.ts';

/**
 * Request to design or optimize a legal workflow process.
 */
export interface ProcessRequest {
  /**
     * Description of the process to design or optimize.
     * @minLength 1
     */
  description: string;
  /** Optional context for process design. Common keys: 'current_steps' (list[str]), 'constraints' (list[str]), 'optimization_goals' (list[str]). All keys are optional. */
  context?: ProcessRequestContext;
}
