/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export interface ProfileQuizRequest {
  /** e.g. 'LLB Year 2', 'JD 1L' */
  year_of_study?: string | null;
  /** e.g. 'Singapore', 'England & Wales' */
  jurisdiction_focus?: string | null;
  /** e.g. ['contract', 'tort', 'criminal'] */
  areas_of_interest?: string[] | null;
}
