/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalSearchFilters } from './legalSearchFilters';

/**
 * Request for proximity search (NEAR/n equivalent).

Finds documents where term1 and term2 appear within `slop` words of each other.
 */
export interface ProximitySearchRequest {
  /**
   * First term or phrase
   * @minLength 1
   */
  term1: string;
  /**
   * Second term or phrase
   * @minLength 1
   */
  term2: string;
  /**
   * Maximum word distance between terms
   * @minimum 1
   * @maximum 100
   */
  slop?: number;
  /** If true, terms must appear in specified order */
  in_order?: boolean;
  /** ISO country code: SG, UK, AU, MY, ID */
  country?: string | null;
  /** Specific ES indices (overrides country) */
  indices?: string[] | null;
  /**
   * Number of results to return
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** Optional filters */
  filters?: LegalSearchFilters | null;
  /** Apply Cohere reranking to improve result relevance */
  rerank?: boolean;
  /**
   * Number of results to return after reranking
   * @minimum 1
   * @maximum 50
   */
  rerank_top_n?: number;
}
