/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Detected optimal search type for the query
 */
export type QueryTypeResponseQueryType = typeof QueryTypeResponseQueryType[keyof typeof QueryTypeResponseQueryType];


export const QueryTypeResponseQueryType = {
  keyword: 'keyword',
  semantic: 'semantic',
  boolean: 'boolean',
  proximity: 'proximity',
  hybrid: 'hybrid',
} as const;
