/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { ReassignedDetail } from './reassignedDetail';

/**
 * Reassignment recorded in legal_request_assignments.
 */
export interface ReassignedEntry {
  timestamp: string;
  userId?: string | null;
  action?: 'reassigned';
  detail?: ReassignedDetail | null;
}
