/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Single item in the recent feed.
 */
export interface RecentFeedItem {
  legisId: string;
  title?: string | null;
  enactedDate?: string | null;
  indexedDate?: string | null;
  jurisdiction?: string | null;
  docType?: string | null;
}
