/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Generic ordering payload used by `.../order` endpoints.
 */
export interface ReorderRequest {
  /** Ordered list of IDs. */
  order?: string[];
}
