/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Metadata for all request.* notification types.

All request transition notifications carry only request_id so the
recipient can navigate to the request.
 */
export interface RequestTransitionMetadata {
  requestId: string;
}
