/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { RequestTransitionMetadata } from './requestTransitionMetadata';

/**
 * Notification sent to requestor when their request is completed.
 */
export interface RequestCompletedNotification {
  id: string;
  title: string;
  body?: string | null;
  read?: boolean;
  createdAt?: string | null;
  type?: 'request.completed';
  metadata?: RequestTransitionMetadata | null;
}
