/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Structured input for a `research` legal request.
 */
export interface ResearchInput {
  type?: 'research';
  /** @minLength 1 */
  question: string;
  jurisdiction?: string | null;
  depth?: 'shallow' | 'standard' | 'deep' | null;
  sources?: ('cases' | 'legislation' | 'secondary')[] | null;
}
