/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional constraints for research. Common keys: 'jurisdiction' (str), 'year_from' (int), 'year_to' (int), 'sources' (list[str]: 'cases'|'legislation'|'secondary'), 'max_depth' (int). All keys are optional.
 */
export type ResearchRequestConstraints = { [key: string]: unknown };
