/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { ResearchRequestConstraints } from './researchRequestConstraints';
import type { ResearchRequestDetailLevel } from './researchRequestDetailLevel';
import type { ResearchRequestPublishFormatsItem } from './researchRequestPublishFormatsItem';
import type { ResearchRequestTemplate } from './researchRequestTemplate';

/**
 * Request to initiate deep legal research on a question.
 */
export interface ResearchRequest {
  /**
   * The legal research question.
   * @minLength 1
   */
  question: string;
  /** Optional constraints for research. Common keys: 'jurisdiction' (str), 'year_from' (int), 'year_to' (int), 'sources' (list[str]: 'cases'|'legislation'|'secondary'), 'max_depth' (int). All keys are optional. */
  constraints?: ResearchRequestConstraints;
  /** Maximum number of report sections */
  maxSections?: number | null;
  /** Export formats to generate (e.g. ['docx', 'pdf']). Empty = markdown only. */
  publishFormats?: ResearchRequestPublishFormatsItem[];
  /** Optional model override */
  model?: string;
  /** Additional research guidelines or focus areas */
  guidelines?: string;
  /** Preferred primary source type (e.g. 'cases', 'legislation') */
  primarySource?: string;
  /** Memo structure template. 'custom' uses custom_sections. */
  template?: ResearchRequestTemplate;
  /** Ordered section headings, used only when template == 'custom'. */
  customSections?: string[];
  /** Jurisdiction to scope the research to (e.g. 'Singapore', 'England') */
  jurisdiction?: string;
  /** Research depth: 'shallow' = concise, 'deep' = exhaustive. */
  detailLevel?: ResearchRequestDetailLevel;
}
