/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Memo structure template. 'custom' uses custom_sections.
 */
export type ResearchRequestTemplate = typeof ResearchRequestTemplate[keyof typeof ResearchRequestTemplate];


export const ResearchRequestTemplate = {
  irac: 'irac',
  cleo: 'cleo',
  standard: 'standard',
  custom: 'custom',
} as const;
