/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional context for review. Common keys: 'jurisdiction' (str), 'document_type' (str), 'playbook_id' (str), 'risk_tolerance' (str: 'low'|'medium'|'high'). All keys are optional.
 */
export type ReviewRequestContext = { [key: string]: unknown };
