/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { ReviewInputReviewType } from './reviewInputReviewType';

/**
 * Structured input for a `review` legal request.
 */
export interface ReviewInput {
  type?: 'review';
  /** @minLength 1 */
  documentId: string;
  reviewType: ReviewInputReviewType;
  focus?: string[] | null;
}
