/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { ReviewResultIssuesItem } from './reviewResultIssuesItem';

/**
 * Result of the `review` job handler.
 */
export interface ReviewResult {
  jobType: 'review';
  summary: string;
  issues?: ReviewResultIssuesItem[];
  status?: string;
}
