/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export type ReviewIssueKind = typeof ReviewIssueKind[keyof typeof ReviewIssueKind];


export const ReviewIssueKind = {
  risk: 'risk',
  ambiguity: 'ambiguity',
  missing: 'missing',
  style: 'style',
  other: 'other',
} as const;
