/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewRequestContext } from './reviewRequestContext';

/**
 * Request to review legal text for issues and suggestions.
 */
export interface ReviewRequest {
  /**
   * The legal text to review.
   * @minLength 1
   */
  text: string;
  /** Optional specific instructions for the review focus. */
  instructions?: string | null;
  /** Optional context for review. Common keys: 'jurisdiction' (str), 'document_type' (str), 'playbook_id' (str), 'risk_tolerance' (str: 'low'|'medium'|'high'). All keys are optional. */
  context?: ReviewRequestContext;
}
