/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Detail for a 'routing.auto_assigned' audit event: routing rules fired on creation.
 */
export interface RoutingAutoAssignedDetail {
  assigneeId: string;
  category?: string | null;
}
