/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { RoutingAutoAssignedDetail } from './routingAutoAssignedDetail';

/**
 * Auto-assignment by routing rules; written to audit_log on request creation.
 */
export interface RoutingAutoAssignedEntry {
  timestamp: string;
  userId?: string | null;
  action?: 'routing.auto_assigned';
  detail?: RoutingAutoAssignedDetail | null;
}
