/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export type RubricDimensionGrade = typeof RubricDimensionGrade[keyof typeof RubricDimensionGrade];


export const RubricDimensionGrade = {
  fail: 'fail',
  weak: 'weak',
  adequate: 'adequate',
  good: 'good',
  very_good: 'very_good',
  excellent: 'excellent',
} as const;
