/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { SearchResultMetadata } from './searchResultMetadata';
import type { SearchSource } from './searchSource';

export interface SearchResult {
  id: string;
  title: string;
  url?: string | null;
  snippet?: string | null;
  source?: SearchSource | null;
  score?: number | null;
  published_at?: string | null;
  metadata?: SearchResultMetadata;
}
