/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export interface SearchItemSource {
  url?: string;
  body?: string;
  title?: string;
  date?: string;
  tags?: string[];
  counsel?: string[] | null;
  coram_structured?: string[][] | null;
  legis_status?: string | null;
  mp_names?: (string | string[])[] | null;
}
