/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request for semantically related documents.
 */
export interface SearchRelateRequest {
  /** The legisId of the document to find related documents for. */
  legis_id?: string | null;
  /** Alternatively, provide an embedding vector directly. */
  embedding?: number[] | null;
}
