/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { SearchSummaryRequestJsonResponse } from './searchSummaryRequestJsonResponse';
import type { StreamFormat } from './streamFormat';
import type { SummaryComplexity } from './summaryComplexity';
import type { SummaryPromptType } from './summaryPromptType';

export interface SearchSummaryRequest {
  /** Search results payload. Typically a JSON dict (e.g. Elasticsearch response). If `compressed=true`, this may be a gzip+base64 string. */
  json_response: SearchSummaryRequestJsonResponse;
  /**
   * The original user query.
   * @minLength 1
   */
  query: string;
  /** Controls the summary style. See `GET /search/summary/prompt-types` for value descriptions. */
  prompt_type?: SummaryPromptType;
  /** Audience complexity level. Controls tone and technical depth. 'layperson' = warm/jargon-free, 'familiar' = professional, 'lawyer' = formal/precise. */
  complexity?: SummaryComplexity;
  /** Set true if `json_response` is a gzip+base64 encoded string. */
  compressed?: boolean | null;
  /** Output format for streaming events. 'type_value' = {type, value} (better for codegen). 'results_cherry' = legacy {context}/{question}/{answer} style. */
  stream_format?: StreamFormat;
}
