/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Jurisdictions with indexed legal data.
 */
export type SearchRegion = typeof SearchRegion[keyof typeof SearchRegion];


export const SearchRegion = {
  SG: 'SG',
  UK: 'UK',
  AU: 'AU',
  MY: 'MY',
  ID: 'ID',
  HK: 'HK',
  CA: 'CA',
  US: 'US',
  US_CA: 'US_CA',
  US_DE: 'US_DE',
  US_MA: 'US_MA',
  US_NY: 'US_NY',
} as const;
