/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Search results payload. Typically a JSON dict (e.g. Elasticsearch response). If `compressed=true`, this may be a gzip+base64 string.
 */
export type SearchSummaryRequestJsonResponse = { [key: string]: unknown } | string;
