/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request for query expansion suggestions.
 */
export interface SearchSuggestionsRequest {
  /**
   * The user's original query.
   * @minLength 1
   */
  query: string;
}
