/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Request for query expansion suggestions.
 */
export interface SearchSuggestionsRequest {
  /**
   * The user's original query.
   * @minLength 1
   */
  query: string;
  /** ISO 3166-1 alpha-2 country code for localising suggestions (e.g. 'SG', 'GB', 'AU'). */
  country?: string | null;
}
