/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Request for documents that cite a given resource.
 */
export interface SearchCiteRequest {
  /**
   * The legisId of the document to find citing documents for.
   * @minLength 1
   */
  legisId: string;
}
