/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response containing alternative query formulations.
 */
export interface SearchSuggestionsResponse {
  /** List of 5 alternative query phrasings for semantic search. */
  query_suggestions?: string[];
}
