/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { HansardSource } from './hansardSource';

export interface SgHansardHit {
  _id?: string | null;
  _score?: number | null;
  _index: 'search-hansard';
  _source: HansardSource;
}
