/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { RegulatorySource } from './regulatorySource';

export interface SgRegHit {
  _id?: string | null;
  _score?: number | null;
  _index: 'search-sg_reg';
  _source: RegulatorySource;
}
