/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export interface SharedBriefcaseItem {
  share_id: string;
  briefcase_id: string;
  briefcase_name: string;
  sharer_id: string;
  permission: string;
  accepted_at?: string | null;
  created_at: string;
}
