/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import { StreamHeartbeatEventType } from './streamHeartbeatEventType';

/**
 * Keep-alive frame for long-running streams (PR-13 / BE.C68).

Receivers MUST accept and silently ignore. NOT a terminal event — the
stream still ends with a `done` or `error` frame after any heartbeats.
Added to prevent Cloud Run idle-proxy disconnects (~60s) from killing
long chat / orchestrate / search-summary sessions.
 */
export interface StreamHeartbeatEvent {
  type: StreamHeartbeatEventType;
  value: string;
}
