/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Stream output format selector.
 */
export type StreamFormat = typeof StreamFormat[keyof typeof StreamFormat];


export const StreamFormat = {
  type_value: 'type_value',
  results_cherry: 'results_cherry',
} as const;
