/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { StreamAnswerEvent } from './streamAnswerEvent';
import type { StreamContextEvent } from './streamContextEvent';
import type { StreamDeltaEvent } from './streamDeltaEvent';
import type { StreamDoneEvent } from './streamDoneEvent';
import type { StreamErrorEvent } from './streamErrorEvent';
import type { StreamHeartbeatEvent } from './streamHeartbeatEvent';
import type { StreamMessageSavedEvent } from './streamMessageSavedEvent';
import type { StreamQuestionEvent } from './streamQuestionEvent';
import type { StreamStatusEvent } from './streamStatusEvent';
import type { StreamThinkingEvent } from './streamThinkingEvent';

export type StreamEvent = StreamStatusEvent | StreamDeltaEvent | StreamThinkingEvent | StreamContextEvent | StreamQuestionEvent | StreamAnswerEvent | StreamMessageSavedEvent | StreamDoneEvent | StreamErrorEvent | StreamHeartbeatEvent;
