/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Payload nested under StreamMessageSavedEvent.value.

Mirrors what the FE needs to attach feedback (thumbs up/down) to the
just-persisted assistant message without a follow-up GET.
 */
export interface StreamMessageSavedValue {
  messageId: string;
}
