/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { SubscriptionDetailStatus } from './subscriptionDetailStatus';

export interface SubscriptionDetail {
  plan: string;
  status: SubscriptionDetailStatus;
  planInterval?: string | null;
  createdAt?: string | null;
  canceledAt?: string | null;
  trialEnd?: string | null;
  currentPeriodEnd?: string | null;
  stripeSubscriptionId: string;
  title?: string | null;
  companyName?: string | null;
  everlasting?: boolean;
}
