/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export type SummaryPromptType = typeof SummaryPromptType[keyof typeof SummaryPromptType];


export const SummaryPromptType = {
  summary: 'summary',
  principles: 'principles',
  themes: 'themes',
  policy_issue_timeline: 'policy_issue_timeline',
  legislative_timeline: 'legislative_timeline',
  sentencing: 'sentencing',
} as const;
