/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { SummariseDocumentRequestStyle } from './summariseDocumentRequestStyle.ts';

export interface SummariseDocumentRequest {
  /** @minLength 1 */
  text: string;
  style?: SummariseDocumentRequestStyle;
}
