/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export type SummariseSearchRequestStyle = typeof SummariseSearchRequestStyle[keyof typeof SummariseSearchRequestStyle];


export const SummariseSearchRequestStyle = {
  brief: 'brief',
  standard: 'standard',
  detailed: 'detailed',
} as const;
