/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Audience complexity level for summary generation.
 */
export type SummaryComplexity = typeof SummaryComplexity[keyof typeof SummaryComplexity];


export const SummaryComplexity = {
  layperson: 'layperson',
  familiar: 'familiar',
  lawyer: 'lawyer',
} as const;
