/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { SearchResult } from './searchResult';
import type { SummariseSearchRequestStyle } from './summariseSearchRequestStyle';

export interface SummariseSearchRequest {
  /** @minLength 1 */
  query: string;
  results: SearchResult[];
  style?: SummariseSearchRequestStyle;
}
