/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { SummariseChatRequestMessagesItem } from './summariseChatRequestMessagesItem';
import type { SummariseChatRequestStyle } from './summariseChatRequestStyle';

export interface SummariseChatRequest {
  /** List of chat message objects; exact shape TBD. */
  messages?: SummariseChatRequestMessagesItem[];
  style?: SummariseChatRequestStyle;
}
