/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { SearchResult } from './searchResult.ts';
import type { SummariseSearchRequestStyle } from './summariseSearchRequestStyle.ts';

export interface SummariseSearchRequest {
  /** @minLength 1 */
  query: string;
  results: SearchResult[];
  style?: SummariseSearchRequestStyle;
}
