/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalDocumentStatus } from './legalDocumentStatus';

/**
 * Single entry in a document's version timeline.
 */
export interface TimelineEntry {
  /** Versioned legisId */
  versioned_id: string;
  effective_date: string;
  end_date?: string | null;
  status?: LegalDocumentStatus | null;
  [key: string]: unknown;
 }
