/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request to translate a full legal document via async job.
 */
export interface TranslateDocumentRequest {
  /**
     * Document text to translate
     * @minLength 1
     */
  text: string;
  /**
     * BCP-47 source language code (e.g. 'id', 'zh', 'ms')
     * @minLength 2
     */
  source_language: string;
  /** Optional model override */
  model?: string;
}
