/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { TranslateResultEnglishChunksItem } from './translateResultEnglishChunksItem';
import type { TranslateResultLegalReviewsItem } from './translateResultLegalReviewsItem';
import type { TranslateResultOriginalChunksItem } from './translateResultOriginalChunksItem';
import type { TranslateResultValidationResult } from './translateResultValidationResult';

/**
 * Result of the `translate` job handler (FinalResult.model_dump() shape).
 */
export interface TranslateResult {
  jobType: 'translate';
  englishChunks?: TranslateResultEnglishChunksItem[];
  originalChunks?: TranslateResultOriginalChunksItem[];
  translationContext?: string[];
  legalReviews?: TranslateResultLegalReviewsItem[];
  validationResult?: TranslateResultValidationResult;
  originalDocument?: string;
}
