/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { TranslateChunkedRequestMetadata } from './translateChunkedRequestMetadata.ts';

export interface TranslateChunkedRequest {
  /** @minLength 1 */
  text: string;
  /**
     * BCP-47-ish, e.g. 'es', 'fr', 'zh'
     * @minLength 2
     */
  target_lang: string;
  /**
     * Approx chunk size for batching.
     * @minimum 500
     * @maximum 20000
     */
  chunk_size_chars?: number;
  metadata?: TranslateChunkedRequestMetadata;
}
