/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export interface TranslateRequest {
  /** @minLength 1 */
  text: string;
  /**
   * BCP-47-ish, e.g. 'es', 'fr', 'zh'
   * @minLength 2
   */
  targetLang: string;
}
