/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Free-form input for an `uncertain` legal request.

The classifier agent reads `question_or_task` at execute time to
infer the concrete request_type.
 */
export interface UncertainInput {
  type?: 'uncertain';
  /** @minLength 1 */
  questionOrTask: string;
}
