/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { LegalSearchFilters } from './legalSearchFilters.ts';
import type { UnifiedSearchRequestMode } from './unifiedSearchRequestMode.ts';
import type { UnifiedSearchRequestSort } from './unifiedSearchRequestSort.ts';

export interface UnifiedSearchRequest {
  /** @minLength 1 */
  query: string;
  /** ISO country code: SG, UK, AU, MY, ID. Selects indices for that jurisdiction. */
  region?: string | null;
  /** Explicit ES indices (overrides region). */
  indexes?: string[] | null;
  /** Search mode. 'auto' detects from query. */
  mode?: UnifiedSearchRequestMode;
  filters?: LegalSearchFilters | null;
  sort?: UnifiedSearchRequestSort;
  /**
     * @minimum 1
     * @maximum 100
     */
  size?: number;
  /** search_after values from previous response for pagination. */
  cursor?: unknown[] | null;
  rerank?: boolean;
  /**
     * @minimum 1
     * @maximum 50
     */
  rerank_top_n?: number;
}
