/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { IndexName } from './indexName';
import type { LegalSearchFilters } from './legalSearchFilters';
import type { SearchRegion } from './searchRegion';
import type { UnifiedSearchRequestMode } from './unifiedSearchRequestMode';
import type { UnifiedSearchRequestSort } from './unifiedSearchRequestSort';

export interface UnifiedSearchRequest {
  /** @minLength 1 */
  query: string;
  /** ISO country code selecting indices for that jurisdiction. US_* codes are state-level. Must match `legal_search.REGION_INDICES`. */
  region?: SearchRegion | null;
  /** Explicit ES indices (overrides region). */
  indexes?: IndexName[] | null;
  /** Search mode. 'auto' detects from query. */
  mode?: UnifiedSearchRequestMode;
  filters?: LegalSearchFilters | null;
  sort?: UnifiedSearchRequestSort;
  /**
   * @minimum 1
   * @maximum 100
   */
  size?: number;
  /** search_after values from previous response for pagination. */
  cursor?: unknown[] | null;
  rerank?: boolean;
  /**
   * @minimum 1
   * @maximum 50
   */
  rerankTopN?: number;
  /** Optional ranking experiment variant (e.g. 'experimental_a'). Logged for A/B analysis. */
  rankingVariant?: string | null;
}
