/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export type UnifiedSearchRequestSort = typeof UnifiedSearchRequestSort[keyof typeof UnifiedSearchRequestSort];


export const UnifiedSearchRequestSort = {
  relevance: 'relevance',
  date_desc: 'date_desc',
  date_asc: 'date_asc',
} as const;
