/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { UnifiedSearchItem } from './unifiedSearchItem';
import type { UnifiedSearchMeta } from './unifiedSearchMeta';
import type { UnifiedSearchResponseAggregations } from './unifiedSearchResponseAggregations';

export interface UnifiedSearchResponse {
  items?: UnifiedSearchItem[];
  aggregations?: UnifiedSearchResponseAggregations;
  meta?: UnifiedSearchMeta;
}
