/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */
import type { UnifiedSearchItem } from './unifiedSearchItem.ts';
import type { UnifiedSearchMeta } from './unifiedSearchMeta.ts';
import type { UnifiedSearchResponseAggregations } from './unifiedSearchResponseAggregations.ts';

export interface UnifiedSearchResponse {
  items?: UnifiedSearchItem[];
  aggregations?: UnifiedSearchResponseAggregations;
  meta?: UnifiedSearchMeta;
}
