/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Search mode. 'auto' detects from query.
 */
export type UnifiedSearchRequestMode = typeof UnifiedSearchRequestMode[keyof typeof UnifiedSearchRequestMode];


export const UnifiedSearchRequestMode = {
  auto: 'auto',
  keyword: 'keyword',
  semantic: 'semantic',
  boolean: 'boolean',
} as const;
