/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { UnknownNotificationMetadata } from './unknownNotificationMetadata';

/**
 * Fallback for notifications sent via /notifications/send with caller-supplied types.

The send and broadcast endpoints accept arbitrary type strings; this variant
absorbs them without validation of the metadata payload.
 */
export interface UnknownNotification {
  id: string;
  title: string;
  body?: string | null;
  read?: boolean;
  createdAt?: string | null;
  type: string;
  metadata?: UnknownNotificationMetadata;
}
