/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { TokenUsage } from './tokenUsage';
import type { UsageResponseMetrics } from './usageResponseMetrics';

export interface UsageResponse {
  orgId: string;
  periodDay: string;
  periodMonth: string;
  metrics: UsageResponseMetrics;
  tokenUsage?: TokenUsage;
}
