/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */

export interface UserDetailResponse {
  id: string;
  email: string;
  name: string;
  orgId: string;
  role?: string | null;
  orgRole?: string | null;
  isActive: boolean;
  banned?: boolean | null;
}
