/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.4.0
 */
import type { WebhookCreateRequestEventType } from './webhookCreateRequestEventType';

export interface WebhookCreateRequest {
  /** Event type to subscribe to */
  eventType: WebhookCreateRequestEventType;
  /** URL to POST events to */
  targetUrl: string;
}
