/**
 * Generated by orval 🍺
 * Do not edit manually.
 * elefant-api
 * Legal AI platform API. Provides search, drafting, review, research, translation, citation checking, and conversational AI for legal professionals.
 * OpenAPI spec version: 0.1.0
 */

export interface WebhookCreateRequest {
  /** Event type to subscribe to */
  event_type: string;
  /**
     * URL to POST events to
     * @minLength 1
     * @maxLength 2083
     */
  target_url: string;
}
